#!/usr/bin/env python3
"""emits the physics constants header both the rom and the host golden tests read, straight from
games/mario/research/physics.json plus the point/behaviour tables in roster.json.
run as: gen_physics.py <physics.json> <roster.json> <out_dir>

the milestone's trap says the bible's numbers must never be hand-transcribed twice, so nothing
downstream of this file carries a literal from the bible - player.c, enemies.c and mario_test.cpp
all include the generated header.
"""

import json
import os
import re
import sys

# the tiers this sub-milestone implements: the five ground/air jump tiers. swim (5) and whirlpool
# (6) exist in the bible but need water areas, which are a later sub-milestone.
GROUND_TIERS = ["0", "1", "2", "3", "4"]


def load(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def find_int(text, pattern, path):
    m = re.search(pattern, text)
    if not m:
        raise SystemExit("gen_physics: %s not found in %s" % (pattern, path))
    return int(m.group(1))


def hex_list(table):
    return [int(table[t], 16) for t in GROUND_TIERS]


def int_list(table):
    return [int(table[t]) for t in GROUND_TIERS]


def tier_bounds(tiers):
    # tiers 0..3 each end at an explicit subpixel bound; tier 4 is everything above the last one
    out = []
    for tier in tiers:
        if tier["index"] > 3:
            break
        out.append(int(tier["subpixels_range"][1]))
    if len(out) != 4:
        raise SystemExit("gen_physics: expected 4 bounded jump tiers, got %d" % len(out))
    return out


def brace(values):
    return "{" + ", ".join(str(v) for v in values) + "}"


def subpixels(px_per_frame):
    # smb's horizontal speeds are a signed byte: high nibble whole px, low nibble 1/16 px, so a
    # px/frame figure is exactly 16x its raw byte. anything finer than a sixteenth is not sourced
    value = px_per_frame * 16.0
    if abs(value - round(value)) > 1e-9:
        raise SystemExit("gen_physics: %r is not a whole number of subpixels" % px_per_frame)
    return int(round(value))


def numeric_prefix(sequence):
    # the roster's chain tables end in a "1-Up (each further)" string; lives are m8's, so the rom
    # keeps awarding the last numeric step and the string entry is dropped here
    out = []
    for value in sequence:
        if not isinstance(value, int):
            break
        out.append(value)
    return out


def build(bible, roster, source_path, roster_path):
    horiz = bible["horizontal_movement"]
    accel = horiz["acceleration"]
    jump = bible["jump_and_gravity"]
    enemy = bible["enemy_movement"]
    hits = bible["interactions"]
    score = roster["score_table"]

    lines = []
    add = lines.append
    add("#ifndef PHYSICS_CONSTANTS_H")
    add("#define PHYSICS_CONSTANTS_H")
    add("// generated by games/mario/tools/gen_physics.py from %s - do not edit" % source_path)
    add("")
    add("// horizontal: speed is smb's signed byte, high nibble whole px + low nibble 1/16 px, so")
    add("// every value below counts subpixels (16 = 1 px). accel bytes feed a 1/256-subpixel")
    add("// accumulator whose carry moves the speed one subpixel.")
    add("#define kMarioMaxWalkSubpx %d" % horiz["max_speed"]["walking"]["subpixels_per_frame"])
    add("#define kMarioMaxRunSubpx %d" % horiz["max_speed"]["running"]["subpixels_per_frame"])
    add("#define kMarioWalkAccel %d" % accel["walk_accel"]["decimal"])
    add("#define kMarioRunAccel %d" % accel["run_accel"]["decimal"])
    add("#define kMarioHighSpeedAccel %d" % accel["high_speed_accel"]["decimal"])
    add("#define kMarioSkidMultiplier %d" % accel["skid_multiplier"]["value"])
    add("#define kMarioSkidStopSubpx %d" % accel["skid_instant_stop_threshold"]["decimal"])
    add("// the two tier thresholds the bible states in prose beside their accel bytes")
    add("#define kMarioAirRunTierSubpx %d"
        % find_int(accel["run_accel"]["when"], r"airborne with \|speed\| >= (\d+)", source_path))
    add("#define kMarioHighSpeedTierSubpx %d"
        % find_int(accel["high_speed_accel"]["when"], r"\|speed\| >= (\d+) subpixels", source_path))
    add("")
    add("// vertical: y speed is whole px; gravity feeds a 1/256-px accumulator whose carry moves")
    add("// the speed one whole px downward. tiers are picked from |x speed| at takeoff.")
    add("#define kMarioJumpTierCount %d" % len(GROUND_TIERS))
    add("#define kMarioJumpBoundCount 4")
    add("#define kMarioJumpTierBoundsInit %s" % brace(tier_bounds(jump["speed_tier_selection"]["tiers"])))
    add("#define kMarioJumpSpeedInit %s" % brace(int_list(jump["initial_vertical_velocity"]["by_tier"])))
    add("#define kMarioGravityRiseInit %s" % brace(hex_list(jump["gravity_rising"]["hex_by_tier"])))
    add("#define kMarioGravityFallInit %s" % brace(hex_list(jump["gravity_falling"]["hex_by_tier"])))
    add("#define kMarioMaxFallPx %d" % jump["max_fall_speed"]["value_px_per_frame"])
    add("// releasing a below this much rise keeps the weak gravity for one more frame")
    add("#define kMarioMinRisePx %d" % jump["variable_jump_height_rule"]["min_rise_before_release_matters_px"])
    add("")
    add("// enemies. the same signed-byte subpixel format the player's speed uses, so a goomba's")
    add("// 0.5 px/frame is the bible's own 0xf8 byte and a kicked shell's 3.0 is its 0x30.")
    add("#define kEnemyWalkSubpx %d"
        % subpixels(enemy["goomba_koopa_walk_speed"]["normal_px_per_frame"]))
    add("#define kEnemyShellSubpx %d" % subpixels(hits["shell_kick_speed"]["px_per_frame"]))
    add("// the stomp kicks the player back up: -3 px/frame off a walker, -4 off a shell")
    add("#define kEnemyStompBouncePx %d" % hits["stomp_bounce"]["normal_enemy_stomp_px_per_frame"])
    add("#define kEnemyShellBouncePx %d" % hits["stomp_bounce"]["shell_or_demote_bounce_px_per_frame"])
    add("")
    add("// m7's powerup chain. the two invincibility windows are smb's 21-frame interval timer")
    add("// already multiplied out, so the rom counts plain frames.")
    add("#define kStarFrames %d" % hits["star_invincibility_duration"]["total_frames"])
    add("#define kInjuryFrames %d" % hits["post_damage_invulnerability_duration"]["total_frames"])
    add("// the fireball: the same signed-byte subpixel speed the player and enemies use, then a")
    add("// whole-px fall speed fed by its own 1/256-px accumulator")
    add("#define kFireballSubpx %d" % subpixels(hits["fireball"]["horizontal_speed_px_per_frame"]))
    add("#define kFireballLaunchDy %d" % hits["fireball"]["initial_vertical_speed_px_per_frame"])
    add("#define kFireballGravity %d" % int(hits["fireball"]["gravity_hex"], 16))
    add("#define kFireballMaxFallPx %d" % hits["fireball"]["max_fall_speed_px_per_frame"])
    add("")
    add("// points, from %s's score table. consecutive stomps and consecutive shell kills each" % roster_path)
    add("// escalate along their own sequence; the rom holds the last step once the table runs out")
    stomps = numeric_prefix(score["stomp_chain_sequence"])
    shells = numeric_prefix(score["shell_kick_chain_sequence"])
    add("#define kStompChainCount %d" % len(stomps))
    add("#define kStompChainInit %s" % brace(stomps))
    add("#define kShellChainCount %d" % len(shells))
    add("#define kShellChainInit %s" % brace(shells))
    add("// a fireball or a star kill pays a flat per-kind figure instead, and starts no chain")
    add("#define kGoombaKillPoints %d" % score["goomba"])
    add("#define kKoopaKillPoints %d" % score["koopa_troopa_fire_or_star"])
    add("")
    add("#endif")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 4:
        print("usage: gen_physics.py <physics.json> <roster.json> <out_dir>", file=sys.stderr)
        return 1

    in_path, roster_path, out_dir = sys.argv[1], sys.argv[2], sys.argv[3]
    os.makedirs(out_dir, exist_ok=True)
    text = build(load(in_path), load(roster_path), in_path, roster_path)
    with open(os.path.join(out_dir, "physics_constants.h"), "w", encoding="utf-8") as f:
        f.write(text)
    print("generated physics_constants.h from %s and %s" % (in_path, roster_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
