#!/usr/bin/env python3
"""emits the physics constants header both the rom and the host golden tests read, straight from
games/mario/research/physics.json. run as: gen_physics.py <physics.json> <out_dir>

the milestone's trap says the bible's numbers must never be hand-transcribed twice, so nothing
downstream of this file carries a literal from the bible - player.c and mario_test.cpp both
include the generated header.
"""

import json
import os
import re
import sys

# the tiers this sub-milestone implements: the five ground/air jump tiers. swim (5) and whirlpool
# (6) exist in the bible but need water areas, which are a later sub-milestone.
GROUND_TIERS = ["0", "1", "2", "3", "4"]


def load(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def find_int(text, pattern, path):
    m = re.search(pattern, text)
    if not m:
        raise SystemExit("gen_physics: %s not found in %s" % (pattern, path))
    return int(m.group(1))


def hex_list(table):
    return [int(table[t], 16) for t in GROUND_TIERS]


def int_list(table):
    return [int(table[t]) for t in GROUND_TIERS]


def tier_bounds(tiers):
    # tiers 0..3 each end at an explicit subpixel bound; tier 4 is everything above the last one
    out = []
    for tier in tiers:
        if tier["index"] > 3:
            break
        out.append(int(tier["subpixels_range"][1]))
    if len(out) != 4:
        raise SystemExit("gen_physics: expected 4 bounded jump tiers, got %d" % len(out))
    return out


def brace(values):
    return "{" + ", ".join(str(v) for v in values) + "}"


def build(bible, source_path):
    horiz = bible["horizontal_movement"]
    accel = horiz["acceleration"]
    jump = bible["jump_and_gravity"]

    lines = []
    add = lines.append
    add("#ifndef PHYSICS_CONSTANTS_H")
    add("#define PHYSICS_CONSTANTS_H")
    add("// generated by games/mario/tools/gen_physics.py from %s - do not edit" % source_path)
    add("")
    add("// horizontal: speed is smb's signed byte, high nibble whole px + low nibble 1/16 px, so")
    add("// every value below counts subpixels (16 = 1 px). accel bytes feed a 1/256-subpixel")
    add("// accumulator whose carry moves the speed one subpixel.")
    add("#define kMarioMaxWalkSubpx %d" % horiz["max_speed"]["walking"]["subpixels_per_frame"])
    add("#define kMarioMaxRunSubpx %d" % horiz["max_speed"]["running"]["subpixels_per_frame"])
    add("#define kMarioWalkAccel %d" % accel["walk_accel"]["decimal"])
    add("#define kMarioRunAccel %d" % accel["run_accel"]["decimal"])
    add("#define kMarioHighSpeedAccel %d" % accel["high_speed_accel"]["decimal"])
    add("#define kMarioSkidMultiplier %d" % accel["skid_multiplier"]["value"])
    add("#define kMarioSkidStopSubpx %d" % accel["skid_instant_stop_threshold"]["decimal"])
    add("// the two tier thresholds the bible states in prose beside their accel bytes")
    add("#define kMarioAirRunTierSubpx %d"
        % find_int(accel["run_accel"]["when"], r"airborne with \|speed\| >= (\d+)", source_path))
    add("#define kMarioHighSpeedTierSubpx %d"
        % find_int(accel["high_speed_accel"]["when"], r"\|speed\| >= (\d+) subpixels", source_path))
    add("")
    add("// vertical: y speed is whole px; gravity feeds a 1/256-px accumulator whose carry moves")
    add("// the speed one whole px downward. tiers are picked from |x speed| at takeoff.")
    add("#define kMarioJumpTierCount %d" % len(GROUND_TIERS))
    add("#define kMarioJumpBoundCount 4")
    add("#define kMarioJumpTierBoundsInit %s" % brace(tier_bounds(jump["speed_tier_selection"]["tiers"])))
    add("#define kMarioJumpSpeedInit %s" % brace(int_list(jump["initial_vertical_velocity"]["by_tier"])))
    add("#define kMarioGravityRiseInit %s" % brace(hex_list(jump["gravity_rising"]["hex_by_tier"])))
    add("#define kMarioGravityFallInit %s" % brace(hex_list(jump["gravity_falling"]["hex_by_tier"])))
    add("#define kMarioMaxFallPx %d" % jump["max_fall_speed"]["value_px_per_frame"])
    add("// releasing a below this much rise keeps the weak gravity for one more frame")
    add("#define kMarioMinRisePx %d" % jump["variable_jump_height_rule"]["min_rise_before_release_matters_px"])
    add("")
    add("#endif")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3:
        print("usage: gen_physics.py <physics.json> <out_dir>", file=sys.stderr)
        return 1

    in_path, out_dir = sys.argv[1], sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)
    text = build(load(in_path), in_path)
    with open(os.path.join(out_dir, "physics_constants.h"), "w", encoding="utf-8") as f:
        f.write(text)
    print("generated physics_constants.h from %s" % in_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
