#!/usr/bin/env python3
"""binds the per-level output of compile_level.py into the one table the rom walks and the one the
host tests plan against. run as: gen_levels.py <gen_dir> [--bank N] <level-id> [<level-id> ...]

nothing here parses a bible: every number comes back out of the headers compile_level.py already
wrote, so the level order in argv is the only thing this tool decides.
"""

import os
import re
import sys


def slug_for(level_id):
    return "level_" + level_id.replace("-", "_")


def to_camel(slug):
    return "".join(part.capitalize() for part in slug.split("_"))


def read_defines(path):
    out = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            m = re.match(r"#define\s+(\w+)\s+(\d+)U?\s*$", line)
            if m:
                out[m.group(1)] = int(m.group(2))
    return out


def write_header(gen_dir, levels, bank):
    path = os.path.join(gen_dir, "levels.h")
    with open(path, "w", encoding="utf-8") as f:
        f.write("#ifndef LEVELS_H\n#define LEVELS_H\n")
        f.write("// generated by games/mario/tools/gen_levels.py - do not edit\n\n")
        for slug, _ in levels:
            f.write('#include "%s.h"\n' % slug)
        f.write("\n#include <stdint.h>\n\n")
        f.write("#define kLevelCount %dU\n" % len(levels))
        f.write("// the table is read twice a level load and never inside a frame, so m8b moved it\n")
        f.write("// off bank 0; level.c switches here and copies the entry it wants into ram\n")
        f.write("#define kLevelTableBank %dU\n" % bank)
        maxima = {
            "LEVEL_MAX_COLUMNS": ("LENGTH_COLUMNS", 0),
            "LEVEL_MAX_BLOCKS": ("BLOCK_COUNT", 1),
            "LEVEL_MAX_ENEMIES": ("ENEMY_COUNT", 1),
            "LEVEL_MAX_OBJECTS": ("OBJECT_COUNT", 1),
        }
        for name, (suffix, floor) in maxima.items():
            value = max([d[slug.upper() + "_" + suffix] for slug, d in levels] + [floor])
            f.write("#define %s %dU\n" % (name, value))
        area_columns = 1
        area_count = 0
        coins = 1
        for slug, d in levels:
            area_count = max(area_count, d[slug.upper() + "_AREA_COUNT"])
            for i in range(d[slug.upper() + "_AREA_COUNT"]):
                area_columns = max(area_columns, d["%s_AREA%d_COLUMNS" % (slug.upper(), i)])
                coins = max(coins, d["%s_AREA%d_COIN_COUNT" % (slug.upper(), i)])
        f.write("#define LEVEL_MAX_COINS %dU\n" % coins)
        f.write("#define LEVEL_MAX_AREA_COLUMNS %dU\n" % area_columns)
        f.write("#define LEVEL_MAX_AREAS %dU\n" % max(1, area_count))
        f.write("// the grid the engine unpacks into ram is sized to the longest level and the\n")
        f.write("// widest sub-area, so a level swap is a refill and never a reallocation\n")
        f.write("#define LEVEL_GRID_COLUMNS %dU\n" % max(area_columns, max(d[slug.upper() + "_LENGTH_COLUMNS"] for slug, d in levels)))
        f.write("#define LEVEL_ROWS %s_ROWS\n" % levels[0][0].upper())
        f.write("#define LEVEL_ROW_STRIDE %s_ROW_STRIDE\n\n" % levels[0][0].upper())

        f.write("// one sub-area of a level: its own banked grid plus the coins and warp pipes in it\n")
        f.write("typedef struct {\n")
        f.write("    uint8_t kind;\n")
        f.write("    uint8_t bank;\n")
        f.write("    uint16_t columns;\n")
        f.write("    uint8_t start_column;\n")
        f.write("    uint8_t start_row;\n")
        f.write("    uint8_t exit_column;\n")
        f.write("    uint8_t exit_top_row;\n")
        f.write("    uint16_t return_column;\n")
        f.write("    uint8_t return_top_row;\n")
        f.write("    uint8_t coin_count;\n")
        f.write("    uint8_t warp_count;\n")
        f.write("    const uint8_t* grid;\n")
        f.write("    const uint8_t* coin_column;\n")
        f.write("    const uint8_t* coin_row;\n")
        f.write("    const uint8_t* warp_column;\n")
        f.write("    const uint8_t* warp_level;\n")
        f.write("} AreaInfo;\n\n")

        f.write("// everything the engine needs to play one level, with the lists that stay in bank 0\n")
        f.write("// as plain pointers and the grid as the one thing level.c has to switch banks for\n")
        f.write("typedef struct {\n")
        f.write("    uint8_t bank;\n")
        f.write("    uint8_t type;\n")
        f.write("    uint16_t timer;\n")
        f.write("    uint16_t columns;\n")
        f.write("    uint16_t start_column;\n")
        f.write("    uint8_t start_row;\n")
        f.write("    uint8_t has_flag;\n")
        f.write("    uint16_t flag_column;\n")
        f.write("    uint8_t flag_top_row;\n")
        f.write("    uint8_t flag_base_row;\n")
        f.write("    uint8_t has_axe;\n")
        f.write("    uint16_t axe_column;\n")
        f.write("    uint8_t axe_row;\n")
        f.write("    uint16_t bridge_x0;\n")
        f.write("    uint16_t bridge_x1;\n")
        f.write("    uint8_t bridge_row;\n")
        f.write("    const uint8_t* grid;\n")
        f.write("    uint8_t block_count;\n")
        f.write("    const uint16_t* block_column;\n")
        f.write("    const uint8_t* block_row;\n")
        f.write("    const uint8_t* block_kind;\n")
        f.write("    const uint8_t* block_content;\n")
        f.write("    uint8_t enemy_count;\n")
        f.write("    const uint16_t* enemy_column;\n")
        f.write("    const uint8_t* enemy_row;\n")
        f.write("    const uint8_t* enemy_kind;\n")
        f.write("    uint8_t object_count;\n")
        f.write("    const uint16_t* object_column;\n")
        f.write("    const uint8_t* object_row;\n")
        f.write("    const uint8_t* object_kind;\n")
        f.write("    const uint8_t* object_param;\n")
        f.write("    uint8_t area_count;\n")
        f.write("    const AreaInfo* areas;\n")
        f.write("} LevelInfo;\n\n")
        f.write("extern const LevelInfo kLevels[kLevelCount];\n\n")
        f.write("#endif\n")


def write_table(gen_dir, levels, bank):
    path = os.path.join(gen_dir, "levels.c")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// generated by games/mario/tools/gen_levels.py - do not edit\n")
        f.write("// the table itself is banked; only the entry being played is copied into ram, and\n")
        f.write("// the per-frame list scans read the bank-0 arrays its pointers name\n")
        f.write("#pragma bank %d\n" % bank)
        f.write('\n#include "levels.h"\n\n')
        for slug, d in levels:
            upper = slug.upper()
            if d[upper + "_AREA_COUNT"] == 0:
                continue
            f.write("static const AreaInfo k%sAreas[%s_AREA_COUNT] = {\n" % (to_camel(slug), upper))
            for i in range(d[upper + "_AREA_COUNT"]):
                name = "%s_AREA%d" % (upper, i)
                f.write("    {%s_KIND, %s_BANK, %s_COLUMNS, %s_START_COLUMN, %s_START_ROW,\n"
                        % (name, name, name, name, name))
                f.write("     %s_EXIT_COLUMN,\n" % name)
                f.write("     %s_EXIT_TOP_ROW, %s_RETURN_COLUMN, %s_RETURN_TOP_ROW, %s_COIN_COUNT,\n"
                        % (name, name, name, name))
                f.write("     %s_WARP_COUNT, (const uint8_t*)%s_area%d_blocks, %s_area%d_coin_column,\n"
                        % (name, slug, i, slug, i))
                f.write("     %s_area%d_coin_row, %s_area%d_warp_column, %s_area%d_warp_level},\n"
                        % (slug, i, slug, i, slug, i))
            f.write("};\n\n")
        f.write("const LevelInfo kLevels[kLevelCount] = {\n")
        for slug, d in levels:
            upper = slug.upper()
            areas = ("k%sAreas" % to_camel(slug)) if d[upper + "_AREA_COUNT"] else "0"
            f.write("    {%s_BANK, %s_TYPE, %s_TIMER, %s_LENGTH_COLUMNS, %s_START_COLUMN, %s_START_ROW,\n"
                    % (upper, upper, upper, upper, upper, upper))
            f.write("     %s_HAS_FLAG, %s_FLAG_COLUMN, %s_FLAG_TOP_ROW, %s_FLAG_BASE_ROW,\n"
                    % (upper, upper, upper, upper))
            f.write("     %s_HAS_AXE, %s_AXE_COLUMN, %s_AXE_ROW, %s_BRIDGE_X0, %s_BRIDGE_X1,\n"
                    % (upper, upper, upper, upper, upper))
            f.write("     %s_BRIDGE_ROW, (const uint8_t*)%s_blocks,\n" % (upper, slug))
            f.write("     %s_BLOCK_COUNT, %s_block_column, %s_block_row, %s_block_kind, %s_block_content,\n"
                    % (upper, slug, slug, slug, slug))
            f.write("     %s_ENEMY_COUNT, %s_enemy_column, %s_enemy_row, %s_enemy_kind,\n"
                    % (upper, slug, slug, slug))
            f.write("     %s_OBJECT_COUNT, %s_object_column, %s_object_row, %s_object_kind,\n"
                    % (upper, slug, slug, slug))
            f.write("     %s_object_param, %s_AREA_COUNT, %s},\n" % (slug, upper, areas))
        f.write("};\n")


def write_host(gen_dir, levels):
    # the host twin's own view of the same table: the tests plan against the compiled grids rather
    # than re-deriving a level from its bible json
    path = os.path.join(gen_dir, "levels_host.h")
    with open(path, "w", encoding="utf-8") as f:
        f.write("#ifndef LEVELS_HOST_H\n#define LEVELS_HOST_H\n")
        f.write("// generated by games/mario/tools/gen_levels.py - do not edit\n\n")
        for slug, _ in levels:
            f.write('#include "%s.h"\n' % slug)
            f.write('#include "%s_grid.h"\n' % slug)
            f.write('#include "%s_probes.h"\n' % slug)
        f.write("\n#include <cstdint>\n\n")
        f.write("inline constexpr int kHostLevelCount = %d;\n" % len(levels))
        f.write("inline constexpr int kHostLevelRows = %s_ROWS;\n\n" % levels[0][0].upper())
        f.write("struct HostArea {\n")
        f.write("    int level;\n    int kind;\n    int columns;\n")
        f.write("    const uint8_t (*grid)[kHostLevelRows];\n")
        f.write("    const LevelWarp* warps;\n    int warp_count;\n")
        f.write("    int exit_column;\n    int exit_top_row;\n");
        f.write("    int return_column;\n    int return_top_row;\n")
        f.write("    int start_column;\n    int start_row;\n};\n\n")
        f.write("struct HostLevel {\n")
        f.write("    int type;\n    int timer;\n    int columns;\n    int start_column;\n    int start_row;\n")
        f.write("    int has_flag;\n    int flag_column;\n    int flag_top_row;\n    int flag_base_row;\n")
        f.write("    int has_axe;\n    int axe_column;\n    int axe_row;\n")
        f.write("    int bridge_x0;\n    int bridge_x1;\n    int bridge_row;\n")
        f.write("    const uint8_t (*grid)[kHostLevelRows];\n")
        f.write("    const LevelBlock* blocks;\n    int block_count;\n")
        f.write("    const LevelEnemy* enemies;\n    int enemy_count;\n")
        f.write("    const LevelObject* objects;\n    int object_count;\n")
        f.write("    const LevelProbe* probes;\n    int probe_count;\n};\n\n")

        f.write("inline constexpr HostLevel kHostLevels[kHostLevelCount] = {\n")
        for slug, d in levels:
            upper = slug.upper()
            camel = to_camel(slug)
            f.write("    {%s_TYPE, %s_TIMER, %s_LENGTH_COLUMNS, %s_START_COLUMN, %s_START_ROW,\n"
                    % (upper, upper, upper, upper, upper))
            f.write("     %s_HAS_FLAG, %s_FLAG_COLUMN, %s_FLAG_TOP_ROW, %s_FLAG_BASE_ROW,\n"
                    % (upper, upper, upper, upper))
            f.write("     %s_HAS_AXE, %s_AXE_COLUMN, %s_AXE_ROW, %s_BRIDGE_X0, %s_BRIDGE_X1,\n"
                    % (upper, upper, upper, upper, upper))
            f.write("     %s_BRIDGE_ROW, k%sGrid, k%sBlocks, k%sBlockCount, k%sEnemies, k%sEnemyCount,\n"
                    % (upper, camel, camel, camel, camel, camel))
            f.write("     k%sObjects, k%sObjectCount, k%sProbes, k%sProbeCount},\n"
                    % (camel, camel, camel, camel))
        f.write("};\n\n")

        rows = []
        for index, (slug, d) in enumerate(levels):
            upper = slug.upper()
            camel = to_camel(slug)
            for i in range(d[upper + "_AREA_COUNT"]):
                name = "%s_AREA%d" % (upper, i)
                rows.append(
                    "    {%d, %s_KIND, %s_COLUMNS, k%sArea%dGrid, k%sArea%dWarps, k%sArea%dWarpCount,\n"
                    "     %s_EXIT_COLUMN, %s_EXIT_TOP_ROW, %s_RETURN_COLUMN, %s_RETURN_TOP_ROW,\n"
                    "     %s_START_COLUMN, %s_START_ROW},\n"
                    % (index, name, name, camel, i, camel, i, camel, i, name, name, name, name,
                       name, name))
        f.write("inline constexpr int kHostAreaCount = %d;\n" % max(1, len(rows)))
        f.write("inline constexpr HostArea kHostAreas[kHostAreaCount] = {\n")
        if rows:
            for row in rows:
                f.write(row)
        else:
            f.write("    {},\n")
        f.write("};\n\n#endif\n")


def main():
    args = sys.argv[1:]
    bank = 7
    if "--bank" in args:
        i = args.index("--bank")
        bank = int(args[i + 1])
        del args[i:i + 2]
    if len(args) < 2:
        print("usage: gen_levels.py <gen_dir> [--bank N] <level-id> [...]", file=sys.stderr)
        return 1
    gen_dir = args[0]
    levels = []
    for level_id in args[1:]:
        slug = slug_for(level_id)
        levels.append((slug, read_defines(os.path.join(gen_dir, slug + ".h"))))

    write_header(gen_dir, levels, bank)
    write_table(gen_dir, levels, bank)
    write_host(gen_dir, levels)
    print("bound %d levels -> %s" % (len(levels), gen_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
