#include "cartridge.hpp"
#include "gameboy.hpp"

// generated by games/mario/tools/compile_level.py; see CMakeLists.txt's mario_level target
#include "level_1_1.h"
#include "level_1_1_probes.h"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iterator>
#include <set>
#include <span>
#include <string>
#include <utility>
#include <vector>

namespace {

std::vector<uint8_t> read_mario_rom() {
    std::ifstream in(MARIO_ROM_PATH, std::ios::binary);
    REQUIRE(in.good());
    return std::vector<uint8_t>(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}

constexpr uint32_t kBootFrames = 120;

// the rows main.c tints and prints to, per games/mario/src/mario.h
constexpr uint32_t kTitleRow = 6;
constexpr uint32_t kPromptRow = 10;

// gbdk's ibm font lands ascii 0x20-0x7f on tiles 0x00-0x5f; space (tile 0) is excluded so a
// span only ever measures real glyphs
constexpr uint8_t kFontFirstTile = 0x00;
constexpr uint8_t kFontLastTile = 0x5F;

void run(gb::Gameboy& gameboy, uint32_t frames) {
    for (uint32_t i = 0; i < frames; ++i) {
        gameboy.run_frame();
    }
}

// leftmost and rightmost bg cell columns on a tile row whose id is in [lo, hi]
std::pair<int, int> glyph_span(const gb::Gameboy& gameboy, uint32_t row, uint8_t lo, uint8_t hi) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    int left = -1;
    int right = -1;
    for (uint32_t cx = 0; cx < 20; ++cx) {
        const uint16_t id = ids[(row * 8 + 3) * gb::kLcdWidth + cx * 8 + 3];
        if ((id & 0x100u) != 0) {
            continue;
        }
        const uint8_t tile = static_cast<uint8_t>(id);
        if (tile >= lo && tile <= hi) {
            if (left < 0) {
                left = static_cast<int>(cx);
            }
            right = static_cast<int>(cx);
        }
    }
    return {left, right};
}

// a 5-bit channel that is not the same as the other two makes the color read as non-gray
bool is_non_gray(uint16_t rgb555) {
    const uint16_t r = rgb555 & 0x1Fu;
    const uint16_t g = (rgb555 >> 5) & 0x1Fu;
    const uint16_t b = (rgb555 >> 10) & 0x1Fu;
    return !(r == g && g == b);
}

void press(gb::Gameboy& gameboy, gb::Button button, uint32_t frames) {
    gameboy.set_button(button, true);
    run(gameboy, frames);
    gameboy.set_button(button, false);
}

// boots, then presses start to enter the debug camera, per games/mario/src/main.c's state machine.
// terrain_init()'s ring fill (16 columns, each a banked read plus two vram writes) runs synchronously
// while the lcd is off; the host's run_frame() approximates real time in whole-frame budgets, so a
// display-off burst this size can outrun a single call and needs a few frames to fully drain before
// per-frame button timing (as goto_xy relies on) is trustworthy again
void enter_camera(gb::Gameboy& gameboy) {
    run(gameboy, kBootFrames);
    press(gameboy, gb::Button::Start, 2);
    run(gameboy, 64);
}

// the kBlock* contract and camera geometry from games/mario/src/mario.h, mirrored the same way
// kTitleRow/kFontFirstTile above already mirror it, so the host test never includes a gbdk header
constexpr uint8_t kBlockEmpty = 0;
constexpr uint8_t kBlockGround = 1;
constexpr uint8_t kBlockBrick = 2;
constexpr uint8_t kBlockQuestion = 3;
constexpr uint8_t kBlockHard = 4;
constexpr uint8_t kBlockPipeTl = 5;
constexpr uint8_t kBlockPipeTr = 6;
constexpr uint8_t kBlockPipeBodyL = 7;
constexpr uint8_t kBlockPipeBodyR = 8;
constexpr uint8_t kBlockStair = 9;
constexpr uint8_t kBlockFlagPole = 10;
constexpr uint8_t kBlockCastle = 11;

constexpr uint16_t kBlockPx = 16;
constexpr uint16_t kScreenWidthPx = 160;
constexpr uint8_t kScyMax = 96;
constexpr uint16_t kMaxWorldX =
    (LEVEL_1_1_LENGTH_COLUMNS * kBlockPx > kScreenWidthPx)
        ? static_cast<uint16_t>(LEVEL_1_1_LENGTH_COLUMNS * kBlockPx - kScreenWidthPx)
        : uint16_t{0};

// tracks the rom's camera position by driving it exactly as main.c does: 2px per frame, one d-pad
// direction per axis, clamped the same way terrain.c clamps. the test never reads rom-private state.
struct Camera {
    uint16_t x = 0;
    uint8_t y = 0;

    void goto_xy(gb::Gameboy& gameboy, uint16_t target_x, uint8_t target_y) {
        while (x != target_x || y != target_y) {
            const bool right = x < target_x;
            const bool left = x > target_x;
            const bool down = y < target_y;
            const bool up = y > target_y;
            gameboy.set_button(gb::Button::Right, right);
            gameboy.set_button(gb::Button::Left, left);
            gameboy.set_button(gb::Button::Down, down);
            gameboy.set_button(gb::Button::Up, up);
            gameboy.run_frame();
            if (right) {
                x = static_cast<uint16_t>(x + 2);
            }
            if (left) {
                x = static_cast<uint16_t>(x - 2);
            }
            if (down) {
                y = static_cast<uint8_t>(y + 2);
            }
            if (up) {
                y = static_cast<uint8_t>(y - 2);
            }
        }
        gameboy.set_button(gb::Button::Right, false);
        gameboy.set_button(gb::Button::Left, false);
        gameboy.set_button(gb::Button::Down, false);
        gameboy.set_button(gb::Button::Up, false);
    }
};

// scy that brings block row `row` fully into the 144px window (see terrain.c's viewport math)
uint8_t scy_for_row(uint8_t row) {
    const uint16_t px = static_cast<uint16_t>(static_cast<uint16_t>(row) * kBlockPx);
    return static_cast<uint8_t>(px < kScyMax ? px : kScyMax);
}

// scx that brings block column `column` fully into the 160px window, clamped to the level's range
uint16_t scx_for_column(uint16_t column) {
    const uint16_t px = static_cast<uint16_t>(column * kBlockPx);
    return px < kMaxWorldX ? px : kMaxWorldX;
}

// the tile id at the world block (column, row)'s top-left 8x8 cell, given the camera sits at
// (cam_x, cam_y); the caller must have parked the camera so the block is actually on screen
uint8_t block_tile(const gb::Gameboy& gameboy, uint16_t column, uint8_t row, uint16_t cam_x, uint8_t cam_y) {
    const uint32_t screen_x = static_cast<uint32_t>(column) * kBlockPx - cam_x;
    const uint32_t screen_y = static_cast<uint32_t>(row) * kBlockPx - cam_y;
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    const uint16_t id = ids[(screen_y + 3) * gb::kLcdWidth + screen_x + 3];
    return static_cast<uint8_t>(id & 0xFFu);
}

// pinned bg tile family ranges per claude-docs/milestones/18-smbd.md's test/tile-id contract and
// the id map recorded in games/mario/src/assets.h
bool tile_in_kind_family(uint8_t tile, uint8_t kind) {
    switch (kind) {
    case kBlockEmpty:
        return tile == 0x00;
    case kBlockGround:
    case kBlockHard:
    case kBlockStair:
        return tile >= 0xA0 && tile <= 0xA3;
    case kBlockBrick:
        return tile >= 0xA4 && tile <= 0xA7;
    case kBlockQuestion:
        return tile >= 0xA8 && tile <= 0xAB;
    case kBlockPipeTl:
    case kBlockPipeTr:
    case kBlockPipeBodyL:
    case kBlockPipeBodyR:
        return tile >= 0xB0 && tile <= 0xB7;
    case kBlockFlagPole:
    case kBlockCastle:
        return tile >= 0xB8 && tile <= 0xBF;
    default:
        return false;
    }
}

// every family a terrain cell may legitimately render as: sky/ground/brick/question/hard/pipe/
// flag/castle share the 0xa0-0xbf block, and the font glyphs cover sky's reused space tile
bool is_known_terrain_family(uint8_t tile) {
    return tile <= 0x5F || (tile >= 0xA0 && tile <= 0xBF);
}

} // namespace

TEST_CASE("mario_rom_declares_a_cgb_mbc5_cart") {
    const std::vector<uint8_t> rom = read_mario_rom();
    REQUIRE(rom.size() == 131072u);

    std::string why;
    auto cart = gb::Cartridge::parse(rom, &why);
    REQUIRE(why.empty());
    REQUIRE(cart.has_value());
    REQUIRE(cart->type() == gb::CartType::Mbc5);
    REQUIRE(cart->has_battery());
    REQUIRE(cart->ram_size() > 0u);
    REQUIRE(cart->cgb());
    REQUIRE(cart->title() == "MARIO");
}

TEST_CASE("mario_boots_to_a_colored_title") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    run(gameboy, kBootFrames);
    REQUIRE(gameboy.cgb_mode());

    const std::span<const uint16_t> colors = gameboy.framebuffer_color();
    std::set<uint16_t> distinct(colors.begin(), colors.end());
    REQUIRE(distinct.size() >= 4u);

    size_t non_gray = 0;
    for (uint16_t c : distinct) {
        if (is_non_gray(c)) {
            ++non_gray;
        }
    }
    REQUIRE(non_gray >= 2u);
}

TEST_CASE("mario_title_text_is_centered") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    run(gameboy, kBootFrames);

    // even-length lines land symmetric around the 20 column grid: left + right == 19
    for (uint32_t row : {kTitleRow, kPromptRow}) {
        const auto [left, right] = glyph_span(gameboy, row, kFontFirstTile + 1, kFontLastTile);
        REQUIRE(left >= 0);
        REQUIRE(left + right == 19);
    }
}

TEST_CASE("mario_boot_is_deterministic") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy first;
    gb::Gameboy second;
    REQUIRE(first.load_rom(rom));
    REQUIRE(second.load_rom(rom));
    run(first, kBootFrames);
    run(second, kBootFrames);

    const std::span<const uint16_t> a = first.framebuffer_color();
    const std::span<const uint16_t> b = second.framebuffer_color();
    REQUIRE(a.size() == b.size());
    REQUIRE(std::equal(a.begin(), a.end(), b.begin()));
}

// the golden test binding bible -> compiler -> rom -> screen: every probe the compiler derived
// from level-1-1.json's terrain runs and blocks must render its expected tile family once its
// block is actually on screen. the test never hand-duplicates the bible's positions.
TEST_CASE("mario_compiler_probes_match_the_rendered_level") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    Camera camera;
    for (uint16_t i = 0; i < kLevel11ProbeCount; ++i) {
        const LevelProbe& probe = kLevel11Probes[i];
        camera.goto_xy(gameboy, scx_for_column(probe.column), scy_for_row(probe.row));
        const uint8_t tile = block_tile(gameboy, probe.column, probe.row, camera.x, camera.y);
        REQUIRE(tile_in_kind_family(tile, probe.kind));
    }
}

TEST_CASE("mario_terrain_streams_without_garbage") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    Camera camera;
    const auto check_visible_cells = [&]() {
        const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
        for (uint32_t ty = 0; ty < 18; ++ty) {
            for (uint32_t tx = 0; tx < 20; ++tx) {
                const uint16_t id = ids[(ty * 8 + 3) * gb::kLcdWidth + tx * 8 + 3];
                REQUIRE(is_known_terrain_family(static_cast<uint8_t>(id & 0xFFu)));
            }
        }
    };

    // scroll the whole derived level, one block at a time, checking every visible cell at each stop
    check_visible_cells();
    while (camera.x < kMaxWorldX) {
        const uint16_t step = std::min<uint16_t>(kBlockPx, static_cast<uint16_t>(kMaxWorldX - camera.x));
        camera.goto_xy(gameboy, static_cast<uint16_t>(camera.x + step), camera.y);
        check_visible_cells();
    }
}

TEST_CASE("mario_scy_pans_within_range") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    const LevelProbe* flag_probe = nullptr;
    for (const auto& probe : kLevel11Probes) {
        if (probe.kind == kBlockFlagPole) {
            flag_probe = &probe;
            break;
        }
    }
    REQUIRE(flag_probe != nullptr);

    Camera camera;
    camera.goto_xy(gameboy, scx_for_column(flag_probe->column), scy_for_row(flag_probe->row));
    REQUIRE(tile_in_kind_family(block_tile(gameboy, flag_probe->column, flag_probe->row, camera.x, camera.y),
                                kBlockFlagPole));

    // panning all the way down scrolls the pole's high row above the window, out of view
    camera.goto_xy(gameboy, camera.x, kScyMax);
    const uint8_t bottom_tile = block_tile(gameboy, flag_probe->column, 14, camera.x, camera.y);
    REQUIRE(tile_in_kind_family(bottom_tile, kBlockGround));

    // holding down well past the max cannot push scy outside the level's 240px height
    press(gameboy, gb::Button::Down, 40);
    REQUIRE(block_tile(gameboy, flag_probe->column, 14, camera.x, camera.y) == bottom_tile);

    // panning back up brings the pole's row back into view
    camera.goto_xy(gameboy, camera.x, scy_for_row(flag_probe->row));
    REQUIRE(tile_in_kind_family(block_tile(gameboy, flag_probe->column, flag_probe->row, camera.x, camera.y),
                                kBlockFlagPole));
}

TEST_CASE("mario_camera_shows_colored_terrain") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    // columns 20-29 hold the opening brick/question pyramid and the first pipe; rows 6-14 (scy
    // maxed) keep both those and the row 13-14 ground on screen together
    Camera camera;
    camera.goto_xy(gameboy, scx_for_column(20), scy_for_row(13));

    const std::span<const uint16_t> colors = gameboy.framebuffer_color();
    const std::set<uint16_t> distinct(colors.begin(), colors.end());
    size_t non_gray = 0;
    for (uint16_t c : distinct) {
        if (is_non_gray(c)) {
            ++non_gray;
        }
    }
    REQUIRE(non_gray >= 5u);
}
