#include "cartridge.hpp"
#include "gameboy.hpp"

// generated by games/mario/tools/compile_level.py; see CMakeLists.txt's mario_level target
#include "level_1_1.h"
#include "level_1_1_grid.h"
#include "level_1_1_probes.h"
// generated by games/mario/tools/gen_physics.py from the research bible; the rom reads the same file
#include "physics_constants.h"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iterator>
#include <set>
#include <span>
#include <string>
#include <utility>
#include <vector>

namespace {

std::vector<uint8_t> read_mario_rom() {
    std::ifstream in(MARIO_ROM_PATH, std::ios::binary);
    REQUIRE(in.good());
    return std::vector<uint8_t>(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}

constexpr uint32_t kBootFrames = 120;

// the rows main.c tints and prints to, per games/mario/src/mario.h
constexpr uint32_t kTitleRow = 6;
constexpr uint32_t kPromptRow = 10;

// gbdk's ibm font lands ascii 0x20-0x7f on tiles 0x00-0x5f; space (tile 0) is excluded so a
// span only ever measures real glyphs
constexpr uint8_t kFontFirstTile = 0x00;
constexpr uint8_t kFontLastTile = 0x5F;

void run(gb::Gameboy& gameboy, uint32_t frames) {
    for (uint32_t i = 0; i < frames; ++i) {
        gameboy.run_frame();
    }
}

// leftmost and rightmost bg cell columns on a tile row whose id is in [lo, hi]
std::pair<int, int> glyph_span(const gb::Gameboy& gameboy, uint32_t row, uint8_t lo, uint8_t hi) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    int left = -1;
    int right = -1;
    for (uint32_t cx = 0; cx < 20; ++cx) {
        const uint16_t id = ids[(row * 8 + 3) * gb::kLcdWidth + cx * 8 + 3];
        if ((id & 0x100u) != 0) {
            continue;
        }
        const uint8_t tile = static_cast<uint8_t>(id);
        if (tile >= lo && tile <= hi) {
            if (left < 0) {
                left = static_cast<int>(cx);
            }
            right = static_cast<int>(cx);
        }
    }
    return {left, right};
}

// a 5-bit channel that is not the same as the other two makes the color read as non-gray
bool is_non_gray(uint16_t rgb555) {
    const uint16_t r = rgb555 & 0x1Fu;
    const uint16_t g = (rgb555 >> 5) & 0x1Fu;
    const uint16_t b = (rgb555 >> 10) & 0x1Fu;
    return !(r == g && g == b);
}

void press(gb::Gameboy& gameboy, gb::Button button, uint32_t frames) {
    gameboy.set_button(button, true);
    run(gameboy, frames);
    gameboy.set_button(button, false);
}

// boots, then presses b to enter the m2 debug camera, per games/mario/src/main.c's state machine
// (start enters play; select is the play camera's look-ahead now, so the debug state moved to b).
// terrain_init()'s ring fill (16 columns, each a banked read plus two vram writes) runs synchronously
// while the lcd is off; the host's run_frame() approximates real time in whole-frame budgets, so a
// display-off burst this size can outrun a single call and needs a few frames to fully drain before
// per-frame button timing (as goto_xy relies on) is trustworthy again
void enter_camera(gb::Gameboy& gameboy) {
    run(gameboy, kBootFrames);
    press(gameboy, gb::Button::B, 2);
    run(gameboy, 64);
}

// same settling rule as enter_camera: start loads 1-1 and drops mario on the bible's start cell
void enter_play(gb::Gameboy& gameboy) {
    run(gameboy, kBootFrames);
    press(gameboy, gb::Button::Start, 2);
    run(gameboy, 64);
}

// the kBlock* contract and camera geometry from games/mario/src/mario.h, mirrored the same way
// kTitleRow/kFontFirstTile above already mirror it, so the host test never includes a gbdk header
constexpr uint8_t kBlockEmpty = 0;
constexpr uint8_t kBlockGround = 1;
constexpr uint8_t kBlockBrick = 2;
constexpr uint8_t kBlockQuestion = 3;
constexpr uint8_t kBlockHard = 4;
constexpr uint8_t kBlockPipeTl = 5;
constexpr uint8_t kBlockPipeTr = 6;
constexpr uint8_t kBlockPipeBodyL = 7;
constexpr uint8_t kBlockPipeBodyR = 8;
constexpr uint8_t kBlockStair = 9;
constexpr uint8_t kBlockFlagPole = 10;
constexpr uint8_t kBlockCastle = 11;

constexpr uint16_t kBlockPx = 16;
constexpr uint16_t kScreenWidthPx = 160;
constexpr uint8_t kScyMax = 96;
constexpr uint16_t kMaxWorldX =
    (LEVEL_1_1_LENGTH_COLUMNS * kBlockPx > kScreenWidthPx)
        ? static_cast<uint16_t>(LEVEL_1_1_LENGTH_COLUMNS * kBlockPx - kScreenWidthPx)
        : uint16_t{0};

// tracks the rom's camera position by driving it exactly as main.c does: 2px per frame, one d-pad
// direction per axis, clamped the same way terrain.c clamps. the test never reads rom-private state.
struct Camera {
    uint16_t x = 0;
    uint8_t y = 0;

    void goto_xy(gb::Gameboy& gameboy, uint16_t target_x, uint8_t target_y) {
        while (x != target_x || y != target_y) {
            const bool right = x < target_x;
            const bool left = x > target_x;
            const bool down = y < target_y;
            const bool up = y > target_y;
            gameboy.set_button(gb::Button::Right, right);
            gameboy.set_button(gb::Button::Left, left);
            gameboy.set_button(gb::Button::Down, down);
            gameboy.set_button(gb::Button::Up, up);
            gameboy.run_frame();
            if (right) {
                x = static_cast<uint16_t>(x + 2);
            }
            if (left) {
                x = static_cast<uint16_t>(x - 2);
            }
            if (down) {
                y = static_cast<uint8_t>(y + 2);
            }
            if (up) {
                y = static_cast<uint8_t>(y - 2);
            }
        }
        gameboy.set_button(gb::Button::Right, false);
        gameboy.set_button(gb::Button::Left, false);
        gameboy.set_button(gb::Button::Down, false);
        gameboy.set_button(gb::Button::Up, false);
    }
};

// scy that brings block row `row` fully into the 144px window (see terrain.c's viewport math)
uint8_t scy_for_row(uint8_t row) {
    const uint16_t px = static_cast<uint16_t>(static_cast<uint16_t>(row) * kBlockPx);
    return static_cast<uint8_t>(px < kScyMax ? px : kScyMax);
}

// scx that brings block column `column` fully into the 160px window, clamped to the level's range
uint16_t scx_for_column(uint16_t column) {
    const uint16_t px = static_cast<uint16_t>(column * kBlockPx);
    return px < kMaxWorldX ? px : kMaxWorldX;
}

// the tile id at the world block (column, row)'s top-left 8x8 cell, given the camera sits at
// (cam_x, cam_y); the caller must have parked the camera so the block is actually on screen
uint8_t block_tile(const gb::Gameboy& gameboy, uint16_t column, uint8_t row, uint16_t cam_x, uint8_t cam_y) {
    const uint32_t screen_x = static_cast<uint32_t>(column) * kBlockPx - cam_x;
    const uint32_t screen_y = static_cast<uint32_t>(row) * kBlockPx - cam_y;
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    const uint16_t id = ids[(screen_y + 3) * gb::kLcdWidth + screen_x + 3];
    return static_cast<uint8_t>(id & 0xFFu);
}

// pinned bg tile family ranges per claude-docs/milestones/18-smbd.md's test/tile-id contract and
// the id map recorded in games/mario/src/assets.h
bool tile_in_kind_family(uint8_t tile, uint8_t kind) {
    switch (kind) {
    case kBlockEmpty:
        return tile == 0x00;
    case kBlockGround:
    case kBlockHard:
    case kBlockStair:
        return tile >= 0xA0 && tile <= 0xA3;
    case kBlockBrick:
        return tile >= 0xA4 && tile <= 0xA7;
    case kBlockQuestion:
        return tile >= 0xA8 && tile <= 0xAB;
    case kBlockPipeTl:
    case kBlockPipeTr:
    case kBlockPipeBodyL:
    case kBlockPipeBodyR:
        return tile >= 0xB0 && tile <= 0xB7;
    case kBlockFlagPole:
    case kBlockCastle:
        return tile >= 0xB8 && tile <= 0xBF;
    default:
        return false;
    }
}

// every family a terrain cell may legitimately render as: sky/ground/brick/question/hard/pipe/
// flag/castle share the 0xa0-0xbf block, and the font glyphs cover sky's reused space tile
bool is_known_terrain_family(uint8_t tile) {
    return tile <= 0x5F || (tile >= 0xA0 && tile <= 0xBF);
}

// --- sub-milestone 3: the player ---------------------------------------------------------------

// mirrors of games/mario/src/mario.h's player geometry, the same way kBlockPx above mirrors it
constexpr uint8_t kMarioFirstTile = 0xE0;
constexpr uint8_t kMarioTilesPerFrame = 4;
constexpr uint8_t kMarioFrameCount = 6;
constexpr uint8_t kMarioLastTile = kMarioFirstTile + kMarioFrameCount * kMarioTilesPerFrame - 1;
constexpr int kFrameIdle = 0;
constexpr int kFrameWalk0 = 1;
constexpr int kFrameWalk2 = 3;
constexpr int kFrameSkid = 4;
constexpr int kFrameJump = 5;
constexpr int kPlayerBoxPx = 16;
// the art keeps column 0 and column 15 of the 16px box transparent, so lit pixels sit one in
constexpr int kMarioArtInset = 1;
constexpr int kPlayScy = kScyMax;

// mario's world y while standing on the bible's start cell, in screen px (scy is pinned in play)
constexpr int kStandTop = static_cast<int>(LEVEL_1_1_START_ROW) * kBlockPx - kPlayerBoxPx - kPlayScy;

struct Mario {
    int left = 0;
    int right = 0;
    int top = 0;
    int frame = -1;
    bool found = false;
};

Mario mario_at(const gb::Gameboy& gameboy) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    Mario m;
    for (size_t i = 0; i < ids.size(); ++i) {
        if ((ids[i] & 0x100u) == 0) {
            continue;
        }
        const uint8_t tile = static_cast<uint8_t>(ids[i]);
        if (tile < kMarioFirstTile || tile > kMarioLastTile) {
            continue;
        }
        const int x = static_cast<int>(i % gb::kLcdWidth);
        const int y = static_cast<int>(i / gb::kLcdWidth);
        if (!m.found || x < m.left) {
            m.left = x;
        }
        if (!m.found || x > m.right) {
            m.right = x;
        }
        if (!m.found || y < m.top) {
            m.top = y;
        }
        m.frame = (tile - kMarioFirstTile) / kMarioTilesPerFrame;
        m.found = true;
    }
    return m;
}

// row 3 of the ground-top tile carries one dark speck every 4 px (see kGroundTiles in assets.c),
// so this scanline's first color-0 ground pixel gives the camera's position mod 4
constexpr int kGroundPhaseRow = 13 * kBlockPx + 3 - kPlayScy;

int ground_phase(const gb::Gameboy& gameboy) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    const std::span<const uint8_t> fb = gameboy.framebuffer();
    for (int x = 0; x < static_cast<int>(gb::kLcdWidth); ++x) {
        const size_t i = static_cast<size_t>(kGroundPhaseRow) * gb::kLcdWidth + static_cast<size_t>(x);
        if ((ids[i] & 0x100u) != 0) {
            continue;
        }
        if (static_cast<uint8_t>(ids[i]) == 0xA0 && fb[i] == 0) {
            return x % 4;
        }
    }
    return -1;
}

// the rom never exposes mario's world x, so the test reconstructs it: once the camera follows, his
// screen x is pinned and the whole displacement shows up in the camera's 4px phase; before that the
// camera is parked and it all shows up in his screen x. no step ever exceeds the 2.5 px/frame run
// cap, so the phase difference is unambiguous mod 4.
struct WorldTracker {
    int phase = 0;
    int screen = 0;

    void sync(const gb::Gameboy& gameboy, const Mario& m) {
        phase = ground_phase(gameboy);
        screen = m.left;
    }

    int step(const gb::Gameboy& gameboy, const Mario& m) {
        const int next = ground_phase(gameboy);
        const int cam = ((phase - next) % 4 + 4) % 4;
        const int moved = cam + (m.left - screen);
        phase = next;
        screen = m.left;
        return moved;
    }
};

// the bible's tables, generated straight from physics.json - the same header player.c reads
constexpr int8_t kJumpSpeed[kMarioJumpTierCount] = kMarioJumpSpeedInit;
constexpr uint8_t kGravityRise[kMarioJumpTierCount] = kMarioGravityRiseInit;
constexpr uint8_t kGravityFall[kMarioJumpTierCount] = kMarioGravityFallInit;

// host-side twin of player.c's vertical step: whole-px speed, a 1/256-px accumulator gravity feeds,
// and the bible's hold-a rule. tier 0 because every arc here starts from a standstill.
struct JumpSim {
    int y = kStandTop;
    int8_t speed = 0;
    uint8_t accum = 0;
    int origin = kStandTop;
    bool grounded = true;
    bool a_prev = false;

    void step(bool a) {
        if (grounded && a && !a_prev) {
            speed = kJumpSpeed[0];
            accum = 0;
            origin = y;
            grounded = false;
        }
        uint8_t force = kGravityFall[0];
        if (speed < 0 && ((a && a_prev) || (origin - y) < kMarioMinRisePx)) {
            force = kGravityRise[0];
        }
        const unsigned sum = static_cast<unsigned>(accum) + force;
        accum = static_cast<uint8_t>(sum);
        if (sum > 0xFFu) {
            speed = static_cast<int8_t>(speed + 1);
            if (speed > kMarioMaxFallPx) {
                speed = kMarioMaxFallPx;
            }
        }
        y += speed;
        // the start cell's floor is flat, so landing is one clamp back onto the standing row
        if (speed >= 0 && y >= kStandTop) {
            y = kStandTop;
            speed = 0;
            accum = 0;
            grounded = true;
        }
        a_prev = a;
    }
};

// drives one jump and returns mario's sprite top per frame. the rom reads the buttons set before
// run_frame i on its own frame i, but that frame is only scanned out one frame later, which is
// what the lag the callers measure accounts for.
std::vector<int> jump_tops(gb::Gameboy& gameboy, int hold_frames, int frames) {
    std::vector<int> tops;
    tops.reserve(static_cast<size_t>(frames));
    for (int i = 0; i < frames; ++i) {
        gameboy.set_button(gb::Button::A, i < hold_frames);
        gameboy.run_frame();
        const Mario m = mario_at(gameboy);
        REQUIRE(m.found);
        tops.push_back(m.top);
    }
    gameboy.set_button(gb::Button::A, false);
    return tops;
}

// the first frame mario's sprite actually moves; everything before it is the rom's scanout lag
int first_move(const std::vector<int>& tops) {
    for (size_t i = 0; i < tops.size(); ++i) {
        if (tops[i] != kStandTop) {
            return static_cast<int>(i);
        }
    }
    return -1;
}

// holds a direction (plus b to run) and returns the world px covered over the whole window
int travel(gb::Gameboy& gameboy, gb::Button dir, bool run_button, int frames) {
    WorldTracker tracker;
    tracker.sync(gameboy, mario_at(gameboy));
    gameboy.set_button(dir, true);
    gameboy.set_button(gb::Button::B, run_button);
    int total = 0;
    for (int i = 0; i < frames; ++i) {
        gameboy.run_frame();
        total += tracker.step(gameboy, mario_at(gameboy));
    }
    return total;
}

// the leftmost screen x carrying a bg pixel of the given tile family on mario's own rows, or -1
int face_of(const gb::Gameboy& gameboy, const Mario& m, uint8_t lo, uint8_t hi) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    const int bottom = std::min(m.top + kPlayerBoxPx, static_cast<int>(gb::kLcdHeight));
    for (int x = 0; x < static_cast<int>(gb::kLcdWidth); ++x) {
        for (int y = std::max(m.top, 0); y < bottom; ++y) {
            const size_t i = static_cast<size_t>(y) * gb::kLcdWidth + static_cast<size_t>(x);
            if ((ids[i] & 0x100u) != 0) {
                continue;
            }
            const uint8_t tile = static_cast<uint8_t>(ids[i]);
            if (tile >= lo && tile <= hi) {
                return x;
            }
        }
    }
    return -1;
}

int pipe_face(const gb::Gameboy& gameboy, const Mario& m) {
    return face_of(gameboy, m, 0xB0, 0xB7);
}

int pole_face(const gb::Gameboy& gameboy, const Mario& m) {
    return face_of(gameboy, m, 0xB8, 0xBF);
}

// the level's first pit, taken from the compiler's own probes rather than the bible's json
uint16_t first_gap_column() {
    for (const auto& probe : kLevel11Probes) {
        if (probe.kind == kBlockEmpty && probe.row == 13) {
            return probe.column;
        }
    }
    return 0;
}

// --- sub-milestone 4: the camera, and a host twin of the rom used to plan 1-1 -------------------

// mirrors of games/mario/src/mario.h's camera and hitbox tuning, same convention as kBlockPx above
constexpr int kCamFollowX = 64;
constexpr int kCamLookAheadX = 24;
constexpr int kCamAnchorStepPx = 2;
constexpr int kCamGroundOffsetPx = 32;
constexpr int kCamPanStepPx = 2;
constexpr int kClearSlidePx = 2;
constexpr int kHitInsetPx = 2;
constexpr int kHitWidthPx = kPlayerBoxPx - 2 * kHitInsetPx;
constexpr int kScreenHeightPx = 144;
constexpr int kLevelHeightPx = 240;

// the planner's own button bits; replay maps them onto gb::Button
constexpr uint8_t kInRight = 0x01;
constexpr uint8_t kInA = 0x02;
constexpr uint8_t kInB = 0x04;

constexpr int kLevelColumns = static_cast<int>(LEVEL_1_1_LENGTH_COLUMNS);
constexpr int kLevelRows = static_cast<int>(LEVEL_1_1_ROWS);

// terrain.c's rule, against the same compiled grid the rom reads out of its banked copy: the level's
// two ends are walls, sky above and the death pit below are not, and the pole is walk-through
bool solid_at(int column, int row) {
    if (column < 0 || column >= kLevelColumns) {
        return true;
    }
    if (row < 0 || row >= kLevelRows) {
        return false;
    }
    const uint8_t kind = kLevel11Grid[column][row];
    return kind != kBlockEmpty && kind != kBlockFlagPole;
}

constexpr uint8_t kJumpTierBounds[kMarioJumpBoundCount] = kMarioJumpTierBoundsInit;

// the host twin of games/mario/src/player.c: the same fixed-point state in the same types, stepped
// in the same order. the planner searches with it, and the autopilot test replays its predictions
// against the rom frame for frame, so any drift between the two is a test failure.
struct PlayerSim {
    int8_t x_speed = 0;
    uint8_t x_accum = 0;
    uint8_t x_force = 0;
    uint16_t x_pos = static_cast<uint16_t>(LEVEL_1_1_START_COLUMN * kBlockPx);
    int8_t y_speed = 0;
    uint8_t y_accum = 0;
    int16_t y_pos = static_cast<int16_t>(LEVEL_1_1_START_ROW * kBlockPx - kPlayerBoxPx);
    int16_t jump_origin_y = y_pos;
    uint8_t on_ground = 1;
    uint8_t jump_tier = 0;
    uint8_t a_prev = 0;

    uint8_t abs_speed() const {
        return static_cast<uint8_t>(x_speed < 0 ? -x_speed : x_speed);
    }

    static int16_t row_of(int16_t py) {
        return py < 0 ? int16_t{-1} : static_cast<int16_t>(py >> 4);
    }

    static int16_t col_of(uint16_t px) {
        return static_cast<int16_t>(px >> 4);
    }

    uint16_t hit_left() const {
        return static_cast<uint16_t>(x_pos + kHitInsetPx);
    }

    uint16_t hit_right() const {
        return static_cast<uint16_t>(x_pos + kHitInsetPx + kHitWidthPx - 1);
    }

    bool fell() const {
        return y_pos >= static_cast<int16_t>(kLevelHeightPx + kPlayerBoxPx);
    }

    bool at_flag() const {
        if (col_of(hit_left()) > static_cast<int16_t>(LEVEL_1_1_FLAG_COLUMN) ||
            col_of(hit_right()) < static_cast<int16_t>(LEVEL_1_1_FLAG_COLUMN)) {
            return false;
        }
        return row_of(y_pos) <= static_cast<int16_t>(LEVEL_1_1_FLAG_BASE_ROW) &&
               row_of(static_cast<int16_t>(y_pos + kPlayerBoxPx - 1)) >=
                   static_cast<int16_t>(LEVEL_1_1_FLAG_TOP_ROW);
    }

    void stop_x() {
        x_speed = 0;
        x_accum = 0;
        x_force = 0;
    }

    void toward_zero(uint8_t delta) {
        if (x_speed > 0) {
            x_speed = static_cast<int8_t>(x_speed - static_cast<int8_t>(delta));
            if (x_speed < 0) {
                x_speed = 0;
            }
        } else if (x_speed < 0) {
            x_speed = static_cast<int8_t>(x_speed + static_cast<int8_t>(delta));
            if (x_speed > 0) {
                x_speed = 0;
            }
        }
    }

    void accelerate(int8_t dir, uint8_t delta, uint8_t max_speed) {
        int16_t next = static_cast<int16_t>(x_speed + dir * static_cast<int16_t>(delta));
        if (next > static_cast<int16_t>(max_speed)) {
            next = static_cast<int16_t>(max_speed);
        }
        if (next < -static_cast<int16_t>(max_speed)) {
            next = static_cast<int16_t>(-static_cast<int16_t>(max_speed));
        }
        x_speed = static_cast<int8_t>(next);
    }

    void step_speed(uint8_t in) {
        const uint8_t run = (in & kInB) != 0 ? 1 : 0;
        const uint8_t speed_abs = abs_speed();
        const int8_t moving_dir = x_speed > 0 ? int8_t{1} : (x_speed < 0 ? int8_t{-1} : int8_t{0});
        const int8_t want_dir = (in & kInRight) != 0 ? int8_t{1} : int8_t{0};
        uint8_t max_speed = kMarioMaxWalkSubpx;
        uint16_t adder = 0;

        const bool skidding = want_dir != 0 && moving_dir != 0 && want_dir != moving_dir;
        if (want_dir == 0 && x_speed == 0) {
            x_accum = 0;
            return;
        }
        if (skidding && speed_abs < kMarioSkidStopSubpx) {
            stop_x();
            return;
        }
        if ((on_ground != 0 && run != 0 && want_dir != 0 && (moving_dir == 0 || moving_dir == want_dir)) ||
            (on_ground == 0 && speed_abs >= kMarioAirRunTierSubpx)) {
            adder = kMarioRunAccel;
        } else if (speed_abs >= kMarioHighSpeedTierSubpx) {
            adder = kMarioHighSpeedAccel;
        } else {
            adder = kMarioWalkAccel;
        }
        if (on_ground != 0) {
            if (run != 0) {
                max_speed = kMarioMaxRunSubpx;
            }
        } else if (speed_abs >= kMarioAirRunTierSubpx) {
            max_speed = kMarioMaxRunSubpx;
        }
        if (skidding) {
            adder = static_cast<uint16_t>(adder * kMarioSkidMultiplier);
        }

        const uint16_t sum = static_cast<uint16_t>(x_accum + adder);
        x_accum = static_cast<uint8_t>(sum);
        const uint8_t delta = static_cast<uint8_t>(sum >> 8);
        if (delta == 0) {
            return;
        }
        if (want_dir == 0 || skidding || speed_abs > max_speed) {
            toward_zero(delta);
        } else {
            accelerate(want_dir, delta, max_speed);
        }
    }

    void move_x() {
        const uint8_t raw = static_cast<uint8_t>(x_speed);
        const uint16_t sum = static_cast<uint16_t>(x_force + ((raw & 0x0Fu) << 4));
        int16_t whole = static_cast<int16_t>(raw >> 4);
        if (whole >= 8) {
            whole = static_cast<int16_t>(whole - 16);
        }
        x_force = static_cast<uint8_t>(sum);
        int16_t next =
            static_cast<int16_t>(static_cast<int16_t>(x_pos) + whole + static_cast<int16_t>(sum >> 8));
        if (next < 0) {
            next = 0;
            stop_x();
        }
        x_pos = static_cast<uint16_t>(next);
    }

    void collide_x() {
        const int16_t top_row = row_of(y_pos);
        const int16_t bottom_row = row_of(static_cast<int16_t>(y_pos + kPlayerBoxPx - 1));
        if (x_speed > 0) {
            const int16_t col = col_of(hit_right());
            if (solid_at(col, top_row) || solid_at(col, bottom_row)) {
                x_pos = static_cast<uint16_t>((col << 4) - kHitInsetPx - kHitWidthPx);
                stop_x();
            }
        } else if (x_speed < 0) {
            const int16_t col = col_of(hit_left());
            if (solid_at(col, top_row) || solid_at(col, bottom_row)) {
                x_pos = static_cast<uint16_t>(((col + 1) << 4) - kHitInsetPx);
                stop_x();
            }
        }
    }

    uint8_t tier_for(uint8_t speed_abs) const {
        for (uint8_t i = 0; i < kMarioJumpBoundCount; ++i) {
            if (speed_abs <= kJumpTierBounds[i]) {
                return i;
            }
        }
        return static_cast<uint8_t>(kMarioJumpTierCount - 1);
    }

    uint8_t gravity_now(uint8_t a_held) const {
        if (y_speed < 0) {
            if ((a_held != 0 && a_prev != 0) ||
                static_cast<int16_t>(jump_origin_y - y_pos) < kMarioMinRisePx) {
                return kGravityRise[jump_tier];
            }
        }
        return kGravityFall[jump_tier];
    }

    void step_vertical(uint8_t in) {
        const uint8_t a_held = (in & kInA) != 0 ? 1 : 0;
        if (on_ground != 0 && a_held != 0 && a_prev == 0) {
            jump_tier = tier_for(abs_speed());
            y_speed = kJumpSpeed[jump_tier];
            y_accum = 0;
            jump_origin_y = y_pos;
            on_ground = 0;
        }
        const unsigned sum = static_cast<unsigned>(y_accum) + gravity_now(a_held);
        y_accum = static_cast<uint8_t>(sum);
        if (sum > 0xFFu) {
            y_speed = static_cast<int8_t>(y_speed + 1);
            if (y_speed > kMarioMaxFallPx) {
                y_speed = kMarioMaxFallPx;
            }
        }
        y_pos = static_cast<int16_t>(y_pos + y_speed);
    }

    void collide_y() {
        const int16_t left_col = col_of(hit_left());
        const int16_t right_col = col_of(hit_right());
        on_ground = 0;
        if (y_speed < 0) {
            const int16_t row = row_of(y_pos);
            if (solid_at(left_col, row) || solid_at(right_col, row)) {
                y_pos = static_cast<int16_t>((row + 1) << 4);
                y_speed = 0;
                y_accum = 0;
            }
            return;
        }
        const int16_t row = row_of(static_cast<int16_t>(y_pos + kPlayerBoxPx - 1));
        if (solid_at(left_col, row) || solid_at(right_col, row)) {
            y_pos = static_cast<int16_t>((row << 4) - kPlayerBoxPx);
            y_speed = 0;
            y_accum = 0;
            on_ground = 1;
            return;
        }
        if ((y_pos & 15) == 0 && (solid_at(left_col, static_cast<int16_t>(row + 1)) ||
                                  solid_at(right_col, static_cast<int16_t>(row + 1)))) {
            y_speed = 0;
            y_accum = 0;
            on_ground = 1;
        }
    }

    void step(uint8_t in) {
        step_speed(in);
        move_x();
        collide_x();
        step_vertical(in);
        collide_y();
        a_prev = (in & kInA) != 0 ? 1 : 0;
    }
};

// the host twin of games/mario/src/camera.c, so the planner can predict mario's screen position
struct CameraSim {
    uint16_t x = 0;
    uint8_t y = 0;
    uint8_t anchor = kCamFollowX;
    uint8_t band = 0;

    static uint8_t band_for(int16_t box_top) {
        int value = box_top + kPlayerBoxPx + kCamGroundOffsetPx - kScreenHeightPx;
        value = std::max(0, std::min(static_cast<int>(kScyMax), value));
        return static_cast<uint8_t>(value);
    }

    void step_x(uint16_t mario_x) {
        const uint16_t want = mario_x > anchor ? static_cast<uint16_t>(mario_x - anchor) : uint16_t{0};
        x = std::min(want, kMaxWorldX);
    }

    void init(const PlayerSim& p) {
        anchor = kCamFollowX;
        band = band_for(p.y_pos);
        y = band;
        step_x(p.x_pos);
    }

    // select and the d-pad pan are never both driven by the planner, so the replayed script only
    // exercises the follow path here; the dedicated camera tests drive the other two by hand
    void update(const PlayerSim& p) {
        step_x(p.x_pos);
        if (p.on_ground != 0) {
            band = band_for(p.y_pos);
        }
        const bool standing = p.on_ground != 0 && p.x_speed == 0;
        if (standing) {
            return;
        }
        if (y < band) {
            y = static_cast<uint8_t>(std::min<int>(band, y + kCamPanStepPx));
        } else if (y > band) {
            y = static_cast<uint8_t>(std::max<int>(band, y - kCamPanStepPx));
        }
    }
};

// how far ahead the planner looks before committing to a jump, and the tail of that window it
// measures to tell "still making progress" from "pinned against a wall"
constexpr int kPlanHorizon = 240;
constexpr int kPlanTail = 60;
constexpr int kPlanTailPx = 8;
constexpr int kPlanGainPx = 8;
// only a fall this soon belongs to the decision being made now; a pit two obstacles away shows up
// inside the progress horizon too and must not veto the jump that clears the obstacle in front
constexpr int kPlanFallHorizon = 110;
// the hold lengths the takeoff search tries, shortest first
constexpr int kPlanHolds[] = {4, 8, 12, 16, 20, 24, 28, 32, 40};

struct Lookahead {
    int fell_at = -1;
    int total = 0;
    int tail = 0;

    bool falls_now() const {
        return fell_at >= 0 && fell_at < kPlanFallHorizon;
    }
};

// runs the level forward from `sim` holding right (and run), with a held for the first `hold`
// frames, and reports how far it got and whether it ended in the death pit
Lookahead look_ahead(PlayerSim sim, int hold) {
    const int start_x = static_cast<int>(sim.x_pos);
    int mid_x = start_x;
    int end_x = start_x;
    Lookahead out;
    for (int i = 0; i < kPlanHorizon; ++i) {
        uint8_t in = kInRight | kInB;
        if (i < hold) {
            in |= kInA;
        }
        sim.step(in);
        end_x = static_cast<int>(sim.x_pos);
        if (i == kPlanHorizon - kPlanTail) {
            mid_x = end_x;
        }
        if (sim.fell()) {
            out.fell_at = i;
            break;
        }
    }
    out.total = end_x - start_x;
    out.tail = end_x - mid_x;
    return out;
}

struct Route {
    std::vector<uint8_t> script;
    PlayerSim end;
    bool reached = false;
};

// the 1-1 planner: hold right and run the whole way, and only spend a jump on a frame where simply
// walking on would fall into a pit or stall against a wall inside the lookahead window. the takeoff
// frame therefore falls out of the search rather than being hand-placed, and the hold length is
// whichever one buys the most ground. `goal` ends the route at a world x; `to_flag` ends it on pole
// contact instead.
Route plan_route(uint16_t goal, bool to_flag, int frame_cap) {
    Route route;
    PlayerSim sim;
    int jump_left = 0;

    for (int frame = 0; frame < frame_cap; ++frame) {
        uint8_t in = kInRight | kInB;
        if (jump_left > 0) {
            in |= kInA;
            --jump_left;
        } else if (sim.on_ground != 0 && sim.a_prev == 0) {
            const Lookahead plain = look_ahead(sim, 0);
            if (plain.falls_now() || (plain.fell_at < 0 && plain.tail < kPlanTailPx)) {
                int best_hold = 0;
                int best_total = plain.falls_now() ? -1 : plain.total;
                for (int hold : kPlanHolds) {
                    const Lookahead tried = look_ahead(sim, hold);
                    if (tried.falls_now() || tried.total <= best_total + kPlanGainPx) {
                        continue;
                    }
                    best_total = tried.total;
                    best_hold = hold;
                }
                if (best_hold > 0) {
                    in |= kInA;
                    jump_left = best_hold - 1;
                }
            }
        }

        route.script.push_back(in);
        sim.step(in);
        if (sim.fell()) {
            break;
        }
        if (to_flag ? sim.at_flag() : (sim.x_pos >= goal && sim.on_ground != 0 && jump_left == 0)) {
            route.reached = true;
            break;
        }
    }
    route.end = sim;
    return route;
}

// replays a planned script on the rom one frame at a time
void replay(gb::Gameboy& gameboy, const std::vector<uint8_t>& script, size_t from, size_t to) {
    for (size_t i = from; i < to && i < script.size(); ++i) {
        const uint8_t in = script[i];
        gameboy.set_button(gb::Button::Right, (in & kInRight) != 0);
        gameboy.set_button(gb::Button::B, (in & kInB) != 0);
        gameboy.set_button(gb::Button::A, (in & kInA) != 0);
        gameboy.run_frame();
    }
    gameboy.set_button(gb::Button::Right, false);
    gameboy.set_button(gb::Button::B, false);
    gameboy.set_button(gb::Button::A, false);
}

// the smallest screen y carrying a bg tile in [lo, hi], or -1; the pan tests read the level's own
// rows off the screen this way instead of asking the rom where its camera is
int first_tile_row(const gb::Gameboy& gameboy, uint8_t lo, uint8_t hi) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    for (size_t i = 0; i < ids.size(); ++i) {
        if ((ids[i] & 0x100u) != 0) {
            continue;
        }
        const uint8_t tile = static_cast<uint8_t>(ids[i]);
        if (tile >= lo && tile <= hi) {
            return static_cast<int>(i / gb::kLcdWidth);
        }
    }
    return -1;
}

// every visible cell is one of the families the terrain may legitimately render as
void require_no_garbage(const gb::Gameboy& gameboy) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    for (uint32_t ty = 0; ty < 18; ++ty) {
        for (uint32_t tx = 0; tx < 20; ++tx) {
            const uint16_t id = ids[(ty * 8 + 3) * gb::kLcdWidth + tx * 8 + 3];
            if ((id & 0x100u) != 0) {
                continue;
            }
            REQUIRE(is_known_terrain_family(static_cast<uint8_t>(id & 0xFFu)));
        }
    }
}

} // namespace

TEST_CASE("mario_rom_declares_a_cgb_mbc5_cart") {
    const std::vector<uint8_t> rom = read_mario_rom();
    REQUIRE(rom.size() == 131072u);

    std::string why;
    auto cart = gb::Cartridge::parse(rom, &why);
    REQUIRE(why.empty());
    REQUIRE(cart.has_value());
    REQUIRE(cart->type() == gb::CartType::Mbc5);
    REQUIRE(cart->has_battery());
    REQUIRE(cart->ram_size() > 0u);
    REQUIRE(cart->cgb());
    REQUIRE(cart->title() == "MARIO");
}

TEST_CASE("mario_boots_to_a_colored_title") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    run(gameboy, kBootFrames);
    REQUIRE(gameboy.cgb_mode());

    const std::span<const uint16_t> colors = gameboy.framebuffer_color();
    std::set<uint16_t> distinct(colors.begin(), colors.end());
    REQUIRE(distinct.size() >= 4u);

    size_t non_gray = 0;
    for (uint16_t c : distinct) {
        if (is_non_gray(c)) {
            ++non_gray;
        }
    }
    REQUIRE(non_gray >= 2u);
}

TEST_CASE("mario_title_text_is_centered") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    run(gameboy, kBootFrames);

    // even-length lines land symmetric around the 20 column grid: left + right == 19
    for (uint32_t row : {kTitleRow, kPromptRow}) {
        const auto [left, right] = glyph_span(gameboy, row, kFontFirstTile + 1, kFontLastTile);
        REQUIRE(left >= 0);
        REQUIRE(left + right == 19);
    }
}

TEST_CASE("mario_boot_is_deterministic") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy first;
    gb::Gameboy second;
    REQUIRE(first.load_rom(rom));
    REQUIRE(second.load_rom(rom));
    run(first, kBootFrames);
    run(second, kBootFrames);

    const std::span<const uint16_t> a = first.framebuffer_color();
    const std::span<const uint16_t> b = second.framebuffer_color();
    REQUIRE(a.size() == b.size());
    REQUIRE(std::equal(a.begin(), a.end(), b.begin()));
}

// the golden test binding bible -> compiler -> rom -> screen: every probe the compiler derived
// from level-1-1.json's terrain runs and blocks must render its expected tile family once its
// block is actually on screen. the test never hand-duplicates the bible's positions.
TEST_CASE("mario_compiler_probes_match_the_rendered_level") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    Camera camera;
    for (uint16_t i = 0; i < kLevel11ProbeCount; ++i) {
        const LevelProbe& probe = kLevel11Probes[i];
        camera.goto_xy(gameboy, scx_for_column(probe.column), scy_for_row(probe.row));
        const uint8_t tile = block_tile(gameboy, probe.column, probe.row, camera.x, camera.y);
        REQUIRE(tile_in_kind_family(tile, probe.kind));
    }
}

TEST_CASE("mario_terrain_streams_without_garbage") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    Camera camera;
    const auto check_visible_cells = [&]() {
        const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
        for (uint32_t ty = 0; ty < 18; ++ty) {
            for (uint32_t tx = 0; tx < 20; ++tx) {
                const uint16_t id = ids[(ty * 8 + 3) * gb::kLcdWidth + tx * 8 + 3];
                REQUIRE(is_known_terrain_family(static_cast<uint8_t>(id & 0xFFu)));
            }
        }
    };

    // scroll the whole derived level, one block at a time, checking every visible cell at each stop
    check_visible_cells();
    while (camera.x < kMaxWorldX) {
        const uint16_t step = std::min<uint16_t>(kBlockPx, static_cast<uint16_t>(kMaxWorldX - camera.x));
        camera.goto_xy(gameboy, static_cast<uint16_t>(camera.x + step), camera.y);
        check_visible_cells();
    }
}

TEST_CASE("mario_scy_pans_within_range") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    const LevelProbe* flag_probe = nullptr;
    for (const auto& probe : kLevel11Probes) {
        if (probe.kind == kBlockFlagPole) {
            flag_probe = &probe;
            break;
        }
    }
    REQUIRE(flag_probe != nullptr);

    Camera camera;
    camera.goto_xy(gameboy, scx_for_column(flag_probe->column), scy_for_row(flag_probe->row));
    REQUIRE(tile_in_kind_family(block_tile(gameboy, flag_probe->column, flag_probe->row, camera.x, camera.y),
                                kBlockFlagPole));

    // panning all the way down scrolls the pole's high row above the window, out of view
    camera.goto_xy(gameboy, camera.x, kScyMax);
    const uint8_t bottom_tile = block_tile(gameboy, flag_probe->column, 14, camera.x, camera.y);
    REQUIRE(tile_in_kind_family(bottom_tile, kBlockGround));

    // holding down well past the max cannot push scy outside the level's 240px height
    press(gameboy, gb::Button::Down, 40);
    REQUIRE(block_tile(gameboy, flag_probe->column, 14, camera.x, camera.y) == bottom_tile);

    // panning back up brings the pole's row back into view
    camera.goto_xy(gameboy, camera.x, scy_for_row(flag_probe->row));
    REQUIRE(tile_in_kind_family(block_tile(gameboy, flag_probe->column, flag_probe->row, camera.x, camera.y),
                                kBlockFlagPole));
}

TEST_CASE("mario_camera_shows_colored_terrain") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    // columns 20-29 hold the opening brick/question pyramid and the first pipe; rows 6-14 (scy
    // maxed) keep both those and the row 13-14 ground on screen together
    Camera camera;
    camera.goto_xy(gameboy, scx_for_column(20), scy_for_row(13));

    const std::span<const uint16_t> colors = gameboy.framebuffer_color();
    const std::set<uint16_t> distinct(colors.begin(), colors.end());
    size_t non_gray = 0;
    for (uint16_t c : distinct) {
        if (is_non_gray(c)) {
            ++non_gray;
        }
    }
    REQUIRE(non_gray >= 5u);
}

TEST_CASE("mario_spawns_standing_on_the_bible_start_cell") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    const Mario m = mario_at(gameboy);
    REQUIRE(m.found);
    REQUIRE(m.top == kStandTop);
    REQUIRE(m.left == static_cast<int>(LEVEL_1_1_START_COLUMN) * kBlockPx + kMarioArtInset);
    REQUIRE(m.right - m.left == kPlayerBoxPx - 1 - 2 * kMarioArtInset);
    REQUIRE(m.frame == kFrameIdle);
}

// the milestone's heart: the arc the rom draws must equal the arc the bible's own constants
// predict, simulated host side with the same 1/256 accumulator semantics, frame for frame
TEST_CASE("mario_golden_jump_arc") {
    const std::vector<uint8_t> rom = read_mario_rom();

    constexpr int kArcFrames = 70;
    gb::Gameboy held;
    REQUIRE(held.load_rom(rom));
    enter_play(held);
    const std::vector<int> hold_tops = jump_tops(held, kArcFrames, kArcFrames);

    const int lag = first_move(hold_tops);
    REQUIRE(lag >= 0);
    REQUIRE(lag <= 2);

    JumpSim sim;
    for (size_t i = static_cast<size_t>(lag); i < hold_tops.size(); ++i) {
        sim.step(true);
        REQUIRE(hold_tops[i] == sim.y);
    }
    // the held arc has to be an arc, not a flat line
    REQUIRE(*std::min_element(hold_tops.begin(), hold_tops.end()) < kStandTop - 60);
    REQUIRE(hold_tops.back() == kStandTop);
}

TEST_CASE("mario_tapped_jump_arc_is_shorter_than_the_held_one") {
    const std::vector<uint8_t> rom = read_mario_rom();

    constexpr int kArcFrames = 70;
    constexpr int kTapFrames = 4;
    gb::Gameboy held;
    REQUIRE(held.load_rom(rom));
    enter_play(held);
    const std::vector<int> hold_tops = jump_tops(held, kArcFrames, kArcFrames);
    const int lag = first_move(hold_tops);
    REQUIRE(lag >= 0);

    gb::Gameboy tapped;
    REQUIRE(tapped.load_rom(rom));
    enter_play(tapped);
    const std::vector<int> tap_tops = jump_tops(tapped, kTapFrames, kArcFrames);
    REQUIRE(first_move(tap_tops) == lag);

    JumpSim sim;
    for (size_t i = static_cast<size_t>(lag); i < tap_tops.size(); ++i) {
        sim.step(static_cast<int>(i) - lag < kTapFrames);
        REQUIRE(tap_tops[i] == sim.y);
    }

    // the hold mechanic is the whole point: releasing early cuts the rise off hard
    const int tap_peak = *std::min_element(tap_tops.begin(), tap_tops.end());
    const int hold_peak = *std::min_element(hold_tops.begin(), hold_tops.end());
    REQUIRE(tap_peak > hold_peak + 20);
    REQUIRE(tap_tops.back() == kStandTop);
}

TEST_CASE("mario_max_speeds_match_the_bible") {
    const std::vector<uint8_t> rom = read_mario_rom();

    constexpr int kRunUp = 80;
    constexpr int kMeasure = 40;
    const auto converged = [&rom](bool run_button) {
        gb::Gameboy gameboy;
        REQUIRE(gameboy.load_rom(rom));
        enter_play(gameboy);
        travel(gameboy, gb::Button::Right, run_button, kRunUp);
        const int moved = travel(gameboy, gb::Button::Right, run_button, kMeasure);
        return static_cast<double>(moved) / kMeasure;
    };

    // 24 and 40 subpixels a frame, 16 subpixels to the pixel; the alternating whole-px steps
    // average out exactly, so a twentieth of a pixel is all the slack this needs
    REQUIRE(std::abs(converged(false) - kMarioMaxWalkSubpx / 16.0) < 0.05);
    REQUIRE(std::abs(converged(true) - kMarioMaxRunSubpx / 16.0) < 0.05);
}

TEST_CASE("mario_skid_turns_slower_than_release") {
    const std::vector<uint8_t> rom = read_mario_rom();

    constexpr int kRunUp = 80;
    constexpr int kCap = 200;
    // px still covered to the right after the run-up, until mario is done shedding that speed
    const auto coast = [&rom](bool reverse) {
        gb::Gameboy gameboy;
        REQUIRE(gameboy.load_rom(rom));
        enter_play(gameboy);
        travel(gameboy, gb::Button::Right, false, kRunUp);
        gameboy.set_button(gb::Button::Right, false);
        gameboy.set_button(gb::Button::Left, reverse);

        WorldTracker tracker;
        tracker.sync(gameboy, mario_at(gameboy));
        int total = 0;
        for (int i = 0; i < kCap; ++i) {
            gameboy.run_frame();
            const Mario m = mario_at(gameboy);
            REQUIRE(m.found);
            total += tracker.step(gameboy, m);
            // a release ends at the idle pose, a reversal the frame the skid pose drops
            if (reverse ? m.frame != kFrameSkid : m.frame == kFrameIdle) {
                break;
            }
        }
        gameboy.set_button(gb::Button::Left, false);
        return total;
    };

    const int released = coast(false);
    const int skidded = coast(true);
    REQUIRE(released > 0);
    REQUIRE(skidded > 0);
    // the bible doubles whichever accel tier applies while facing fights motion
    REQUIRE(skidded * 2 < released);
}

TEST_CASE("mario_wall_stops_motion") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    // 1-1's first pipe is a few hundred px out; running there takes well under this many frames
    travel(gameboy, gb::Button::Right, true, 260);
    const Mario m = mario_at(gameboy);
    REQUIRE(m.found);
    REQUIRE(m.top == kStandTop);

    // the hitbox stops 2 px inside the sprite, and the art starts 1 px inside that, so the shoulder
    // overhangs the pipe by exactly one pixel column: mario's last lit column is the pipe's first
    const int face = pipe_face(gameboy, m);
    REQUIRE(face >= 0);
    REQUIRE(m.right == face);

    // nothing moves while the wall is held against
    const int moved = travel(gameboy, gb::Button::Right, true, 60);
    REQUIRE(moved == 0);
    const Mario after = mario_at(gameboy);
    REQUIRE(after.top == kStandTop);
    REQUIRE(pipe_face(gameboy, after) == face);
}

TEST_CASE("mario_landing_snaps_without_sinking") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    // 600 frames of hopping in place, checking he never sinks past the row he took off from
    int hops = 0;
    for (int i = 0; i < 600; ++i) {
        gameboy.set_button(gb::Button::A, (i % 60) < 8);
        gameboy.run_frame();
        const Mario m = mario_at(gameboy);
        REQUIRE(m.found);
        REQUIRE(m.top <= kStandTop);
        if (m.frame == kFrameJump) {
            ++hops;
        }
    }
    gameboy.set_button(gb::Button::A, false);
    run(gameboy, 60);
    REQUIRE(hops > 100);
    REQUIRE(mario_at(gameboy).top == kStandTop);
}

TEST_CASE("mario_animation_changes_with_state") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);
    REQUIRE(mario_at(gameboy).frame == kFrameIdle);

    std::set<int> walking;
    gameboy.set_button(gb::Button::Right, true);
    for (int i = 0; i < 90; ++i) {
        gameboy.run_frame();
        const Mario m = mario_at(gameboy);
        REQUIRE(m.found);
        if (m.frame >= kFrameWalk0 && m.frame <= kFrameWalk2) {
            walking.insert(m.frame);
        }
    }
    REQUIRE(walking.size() >= 2u);

    // a jump swaps in the jump pose for the airborne stretch
    std::set<int> airborne;
    gameboy.set_button(gb::Button::A, true);
    for (int i = 0; i < 20; ++i) {
        gameboy.run_frame();
        airborne.insert(mario_at(gameboy).frame);
    }
    gameboy.set_button(gb::Button::A, false);
    gameboy.set_button(gb::Button::Right, false);
    REQUIRE(airborne.count(kFrameJump) == 1u);

    // reversing at speed shows the skid pose
    run(gameboy, 60);
    gameboy.set_button(gb::Button::Right, true);
    run(gameboy, 60);
    gameboy.set_button(gb::Button::Right, false);
    gameboy.set_button(gb::Button::Left, true);
    std::set<int> turning;
    for (int i = 0; i < 8; ++i) {
        gameboy.run_frame();
        turning.insert(mario_at(gameboy).frame);
    }
    gameboy.set_button(gb::Button::Left, false);
    REQUIRE(turning.count(kFrameSkid) == 1u);
}

TEST_CASE("mario_play_is_deterministic") {
    const std::vector<uint8_t> rom = read_mario_rom();

    const auto drive = [&rom]() {
        gb::Gameboy gameboy;
        REQUIRE(gameboy.load_rom(rom));
        enter_play(gameboy);
        for (int i = 0; i < 240; ++i) {
            gameboy.set_button(gb::Button::Right, (i % 40) < 30);
            gameboy.set_button(gb::Button::B, (i % 80) < 40);
            gameboy.set_button(gb::Button::A, (i % 25) < 10);
            gameboy.run_frame();
        }
        const std::span<const uint16_t> colors = gameboy.framebuffer_color();
        return std::vector<uint16_t>(colors.begin(), colors.end());
    };

    REQUIRE(drive() == drive());
}

// --- sub-milestone 4: the camera ----------------------------------------------------------------

TEST_CASE("mario_camera_follows_and_scrolls_back") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    // at the level start the camera is pinned against the left end, so mario sits at his world x
    REQUIRE(mario_at(gameboy).left == kMarioArtInset);

    // running right hands him to the camera, which then holds him at the follow anchor
    travel(gameboy, gb::Button::Right, true, 200);
    gameboy.set_button(gb::Button::Right, false);
    gameboy.set_button(gb::Button::B, false);
    run(gameboy, 30);
    REQUIRE(mario_at(gameboy).left == kCamFollowX + kMarioArtInset);

    // walking back is the smbd difference: the camera retreats with him instead of locking, which
    // shows up as the ground sliding under a mario whose screen x never moves
    int anchored_scrolls = 0;
    int phase = ground_phase(gameboy);
    gameboy.set_button(gb::Button::Left, true);
    for (int i = 0; i < 700; ++i) {
        gameboy.run_frame();
        const Mario m = mario_at(gameboy);
        REQUIRE(m.found);
        const int next = ground_phase(gameboy);
        if (m.left == kCamFollowX + kMarioArtInset && next != phase) {
            ++anchored_scrolls;
        }
        phase = next;
        require_no_garbage(gameboy);
    }
    gameboy.set_button(gb::Button::Left, false);
    REQUIRE(anchored_scrolls > 100);

    // and the retreat stops dead at the level start: mario ends against the opening wall with the
    // camera clamped back at 0, and leaning on left longer changes neither
    run(gameboy, 60);
    REQUIRE(mario_at(gameboy).left == kMarioArtInset);
    press(gameboy, gb::Button::Left, 120);
    run(gameboy, 10);
    REQUIRE(mario_at(gameboy).left == kMarioArtInset);
}

TEST_CASE("mario_camera_manual_pan") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    // walk up under the opening pyramid. its lower question block sits inside the default ground
    // band and the upper one, four block rows higher, sits just above it: that upper row is the
    // probe a pan has to reveal and a cancelled pan has to hide again
    const LevelProbe* high_probe = nullptr;
    for (const auto& probe : kLevel11Probes) {
        if (probe.kind == kBlockQuestion && probe.row == 5) {
            high_probe = &probe;
            break;
        }
    }
    REQUIRE(high_probe != nullptr);

    int walked = 0;
    const int target = static_cast<int>(high_probe->column) * kBlockPx;
    while (walked < target) {
        walked += travel(gameboy, gb::Button::Right, false, 8);
    }
    gameboy.set_button(gb::Button::Right, false);
    run(gameboy, 90);

    // the band shows the row 9 block and nothing above it
    const int grounded_row = first_tile_row(gameboy, 0xA8, 0xAB);
    REQUIRE(grounded_row == 9 * kBlockPx - kScyMax);

    // standing still, up pans the view 2 px a frame: 24 px of pan slides the level down screen and
    // brings the row 5 block into view four rows above where the row 9 one now sits
    press(gameboy, gb::Button::Up, 12);
    run(gameboy, 4);
    const int panned_row = first_tile_row(gameboy, 0xA8, 0xAB);
    REQUIRE(panned_row == 5 * kBlockPx - (kScyMax - 24));
    REQUIRE(panned_row < grounded_row);

    // walking cancels it: the view drifts back to the ground band on its own, and the drift only
    // runs while he is moving, so a short walk plus the slide-down to a stop is enough
    travel(gameboy, gb::Button::Right, false, 20);
    gameboy.set_button(gb::Button::Right, false);
    run(gameboy, 90);
    REQUIRE(first_tile_row(gameboy, 0xA8, 0xAB) == grounded_row);

    // and the pan is refused outright while airborne, however hard up is held
    gameboy.set_button(gb::Button::A, true);
    gameboy.set_button(gb::Button::Up, true);
    for (int i = 0; i < 20; ++i) {
        gameboy.run_frame();
        REQUIRE(first_tile_row(gameboy, 0xA8, 0xAB) == grounded_row);
    }
    gameboy.set_button(gb::Button::A, false);
    gameboy.set_button(gb::Button::Up, false);
    run(gameboy, 60);
    REQUIRE(first_tile_row(gameboy, 0xA8, 0xAB) == grounded_row);
}

TEST_CASE("mario_camera_select_look_ahead") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    travel(gameboy, gb::Button::Right, true, 200);
    gameboy.set_button(gb::Button::Right, false);
    gameboy.set_button(gb::Button::B, false);
    run(gameboy, 30);
    REQUIRE(mario_at(gameboy).left == kCamFollowX + kMarioArtInset);

    // holding select slides the anchor forward 2 px a frame without moving mario himself
    gameboy.set_button(gb::Button::Select, true);
    run(gameboy, 5);
    const int part_way = mario_at(gameboy).left;
    REQUIRE(part_way < kCamFollowX + kMarioArtInset);
    REQUIRE(part_way > kCamLookAheadX + kMarioArtInset);
    run(gameboy, 40);
    REQUIRE(mario_at(gameboy).left == kCamLookAheadX + kMarioArtInset);

    // and holding it longer cannot push the anchor past the look-ahead spot
    run(gameboy, 60);
    REQUIRE(mario_at(gameboy).left == kCamLookAheadX + kMarioArtInset);

    // releasing slides it back the same way
    gameboy.set_button(gb::Button::Select, false);
    run(gameboy, 5);
    const int coming_back = mario_at(gameboy).left;
    REQUIRE(coming_back > kCamLookAheadX + kMarioArtInset);
    REQUIRE(coming_back < kCamFollowX + kMarioArtInset);
    run(gameboy, 40);
    REQUIRE(mario_at(gameboy).left == kCamFollowX + kMarioArtInset);
}

TEST_CASE("mario_terrain_streams_backward_without_garbage") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    // 60 columns out and 60 back, checking the whole visible grid at every block boundary; the ring
    // has to refill from its left edge on the way home exactly as it did from its right on the way out
    Camera camera;
    constexpr int kColumns = 60;
    require_no_garbage(gameboy);
    for (int i = 0; i < kColumns; ++i) {
        camera.goto_xy(gameboy, static_cast<uint16_t>(camera.x + kBlockPx), camera.y);
        require_no_garbage(gameboy);
    }
    for (int i = 0; i < kColumns; ++i) {
        camera.goto_xy(gameboy, static_cast<uint16_t>(camera.x - kBlockPx), camera.y);
        require_no_garbage(gameboy);
    }
    REQUIRE(camera.x == 0);

    // back at the start the opening ground reads as ground again, not as a stale far-level column
    camera.goto_xy(gameboy, 0, kScyMax);
    REQUIRE(tile_in_kind_family(block_tile(gameboy, 0, 13, camera.x, camera.y), kBlockGround));
}

TEST_CASE("mario_pits_swallow_him_at_the_first_gap") {
    const std::vector<uint8_t> rom = read_mario_rom();
    const uint16_t gap = first_gap_column();
    REQUIRE(gap > 0u);

    // ride the planner up to the flat ground well before the first pit, then just keep walking: the
    // narrowed hitbox means the far lip cannot catch him, so walking off the edge is a fall
    const Route approach = plan_route(static_cast<uint16_t>((gap - 6) * kBlockPx), false, 4000);
    REQUIRE(approach.reached);

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);
    replay(gameboy, approach.script, 0, approach.script.size());

    bool fell = false;
    int last_top = kStandTop;
    gameboy.set_button(gb::Button::Right, true);
    for (int i = 0; i < 240 && !fell; ++i) {
        gameboy.run_frame();
        const Mario m = mario_at(gameboy);
        if (!m.found) {
            fell = last_top > kStandTop;
            continue;
        }
        // he must never come to rest on the pit's far lip on the way down
        REQUIRE(!(m.top == kStandTop && last_top > kStandTop));
        last_top = m.top;
    }
    gameboy.set_button(gb::Button::Right, false);
    REQUIRE(fell);

    // and the respawn puts him back on the bible's start cell with the camera back at the level start
    run(gameboy, 90);
    const Mario back = mario_at(gameboy);
    REQUIRE(back.found);
    REQUIRE(back.top == kStandTop);
    REQUIRE(back.left == static_cast<int>(LEVEL_1_1_START_COLUMN) * kBlockPx + kMarioArtInset);
}

// the traversal milestone's heart: a route the host planner searched out of the compiled level and
// the bible's own physics constants, replayed against the rom frame for frame. the rom has to put
// mario exactly where the twin says on every frame, reach the pole, and run the clear sequence.
TEST_CASE("mario_autopilot_completes_1_1") {
    const std::vector<uint8_t> rom = read_mario_rom();

    const Route route = plan_route(0, true, 4000);
    REQUIRE(route.reached);
    // contact lands on the compiled flag column, not somewhere the route wandered into
    REQUIRE(PlayerSim::col_of(route.end.hit_right()) == static_cast<int16_t>(LEVEL_1_1_FLAG_COLUMN));
    REQUIRE(route.end.x_pos > static_cast<uint16_t>((LEVEL_1_1_FLAG_COLUMN - 2) * kBlockPx));

    // the twin's per-frame screen prediction for mario's sprite box, camera included
    std::vector<std::pair<int, int>> want;
    want.reserve(route.script.size());
    {
        PlayerSim player;
        CameraSim camera;
        camera.init(player);
        for (uint8_t in : route.script) {
            player.step(in);
            camera.update(player);
            want.emplace_back(static_cast<int>(player.x_pos) - static_cast<int>(camera.x),
                              static_cast<int>(player.y_pos) - static_cast<int>(camera.y));
        }
    }

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    std::vector<std::pair<int, int>> saw;
    saw.reserve(route.script.size());
    for (size_t i = 0; i < route.script.size(); ++i) {
        replay(gameboy, route.script, i, i + 1);
        const Mario m = mario_at(gameboy);
        saw.emplace_back(m.found ? m.left - kMarioArtInset : -1000, m.found ? m.top : -1000);
    }

    // the rom scans a frame out one or two frames after it computes it (see jump_tops); whichever
    // lag it is, every frame with mario fully on screen has to agree with the twin exactly
    int matched = 0;
    int best_lag = -1;
    for (int lag = 0; lag <= 3 && best_lag < 0; ++lag) {
        int hits = 0;
        bool ok = true;
        for (size_t i = static_cast<size_t>(lag); i < saw.size() && ok; ++i) {
            const auto [wx, wy] = want[i - static_cast<size_t>(lag)];
            if (wx < 0 || wx > static_cast<int>(gb::kLcdWidth) - kPlayerBoxPx || wy < 0 ||
                wy > kScreenHeightPx - kPlayerBoxPx) {
                continue;
            }
            ok = saw[i] == std::pair<int, int>{wx, wy};
            ++hits;
        }
        if (ok && hits > static_cast<int>(saw.size()) / 2) {
            best_lag = lag;
            matched = hits;
        }
    }
    REQUIRE(best_lag >= 0);
    REQUIRE(matched > 400);

    // the clear sequence owns him from here: he slides down the pole with no input at all. the two
    // opening frames are the rom's own scanout lag showing the last pre-contact frame
    const Mario grabbed = mario_at(gameboy);
    REQUIRE(grabbed.found);
    int prev_top = grabbed.top;
    int descents = 0;
    int held_pole = 0;
    bool feet_on_ground = false;
    for (int i = 0; i < 400; ++i) {
        gameboy.run_frame();
        const Mario m = mario_at(gameboy);
        if (!m.found) {
            continue;
        }
        const int pole = pole_face(gameboy, m);
        if (i >= 2) {
            // snapped onto the pole: mario's sprite box is the pole block, so his art (one column
            // in) starts exactly one pixel right of the block the pole is painted in. he only
            // leaves that alignment when the hop carries him off the base
            if (pole < 0 || m.left - pole != kMarioArtInset) {
                break;
            }
            ++held_pole;
            // the slide's end: his feet come to rest on the ground row beside the pole's base
            if (m.top + kPlayerBoxPx == first_tile_row(gameboy, 0xA0, 0xA0)) {
                feet_on_ground = true;
            }
        }
        if (m.top > prev_top) {
            ++descents;
        }
        prev_top = m.top;
    }
    // the slide runs at a constant kClearSlidePx a frame from wherever contact happened down to the
    // pole's base row, so its length is arithmetic rather than a guess; the hop breaks the pole
    // alignment on the frame after it lands
    const int base_y = (static_cast<int>(LEVEL_1_1_FLAG_BASE_ROW) + 1) * kBlockPx - kPlayerBoxPx;
    const int slide_frames = (base_y - route.end.y_pos + kClearSlidePx - 1) / kClearSlidePx;
    REQUIRE(slide_frames > 40);
    REQUIRE(held_pole >= slide_frames - 4);
    REQUIRE(held_pole <= slide_frames + 4);
    REQUIRE(descents > 8);
    REQUIRE(feet_on_ground);

    // the walk off the pole, the level-clear beat, and back to the title card
    bool titled = false;
    for (int i = 0; i < 600 && !titled; ++i) {
        gameboy.run_frame();
        const auto [left, right] = glyph_span(gameboy, kTitleRow, kFontFirstTile + 1, kFontLastTile);
        titled = left >= 0 && left + right == 19;
    }
    REQUIRE(titled);
    const auto [prompt_left, prompt_right] =
        glyph_span(gameboy, kPromptRow, kFontFirstTile + 1, kFontLastTile);
    REQUIRE(prompt_left >= 0);
    REQUIRE(prompt_left + prompt_right == 19);
}
