#include "cartridge.hpp"
#include "gameboy.hpp"

// generated by games/mario/tools/compile_level.py; see CMakeLists.txt's mario_level target
#include "level_1_1.h"
#include "level_1_1_probes.h"
// generated by games/mario/tools/gen_physics.py from the research bible; the rom reads the same file
#include "physics_constants.h"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iterator>
#include <set>
#include <span>
#include <string>
#include <utility>
#include <vector>

namespace {

std::vector<uint8_t> read_mario_rom() {
    std::ifstream in(MARIO_ROM_PATH, std::ios::binary);
    REQUIRE(in.good());
    return std::vector<uint8_t>(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}

constexpr uint32_t kBootFrames = 120;

// the rows main.c tints and prints to, per games/mario/src/mario.h
constexpr uint32_t kTitleRow = 6;
constexpr uint32_t kPromptRow = 10;

// gbdk's ibm font lands ascii 0x20-0x7f on tiles 0x00-0x5f; space (tile 0) is excluded so a
// span only ever measures real glyphs
constexpr uint8_t kFontFirstTile = 0x00;
constexpr uint8_t kFontLastTile = 0x5F;

void run(gb::Gameboy& gameboy, uint32_t frames) {
    for (uint32_t i = 0; i < frames; ++i) {
        gameboy.run_frame();
    }
}

// leftmost and rightmost bg cell columns on a tile row whose id is in [lo, hi]
std::pair<int, int> glyph_span(const gb::Gameboy& gameboy, uint32_t row, uint8_t lo, uint8_t hi) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    int left = -1;
    int right = -1;
    for (uint32_t cx = 0; cx < 20; ++cx) {
        const uint16_t id = ids[(row * 8 + 3) * gb::kLcdWidth + cx * 8 + 3];
        if ((id & 0x100u) != 0) {
            continue;
        }
        const uint8_t tile = static_cast<uint8_t>(id);
        if (tile >= lo && tile <= hi) {
            if (left < 0) {
                left = static_cast<int>(cx);
            }
            right = static_cast<int>(cx);
        }
    }
    return {left, right};
}

// a 5-bit channel that is not the same as the other two makes the color read as non-gray
bool is_non_gray(uint16_t rgb555) {
    const uint16_t r = rgb555 & 0x1Fu;
    const uint16_t g = (rgb555 >> 5) & 0x1Fu;
    const uint16_t b = (rgb555 >> 10) & 0x1Fu;
    return !(r == g && g == b);
}

void press(gb::Gameboy& gameboy, gb::Button button, uint32_t frames) {
    gameboy.set_button(button, true);
    run(gameboy, frames);
    gameboy.set_button(button, false);
}

// boots, then presses select to enter the debug camera, per games/mario/src/main.c's state machine
// (start now enters the play state instead).
// terrain_init()'s ring fill (16 columns, each a banked read plus two vram writes) runs synchronously
// while the lcd is off; the host's run_frame() approximates real time in whole-frame budgets, so a
// display-off burst this size can outrun a single call and needs a few frames to fully drain before
// per-frame button timing (as goto_xy relies on) is trustworthy again
void enter_camera(gb::Gameboy& gameboy) {
    run(gameboy, kBootFrames);
    press(gameboy, gb::Button::Select, 2);
    run(gameboy, 64);
}

// same settling rule as enter_camera: start loads 1-1 and drops mario on the bible's start cell
void enter_play(gb::Gameboy& gameboy) {
    run(gameboy, kBootFrames);
    press(gameboy, gb::Button::Start, 2);
    run(gameboy, 64);
}

// the kBlock* contract and camera geometry from games/mario/src/mario.h, mirrored the same way
// kTitleRow/kFontFirstTile above already mirror it, so the host test never includes a gbdk header
constexpr uint8_t kBlockEmpty = 0;
constexpr uint8_t kBlockGround = 1;
constexpr uint8_t kBlockBrick = 2;
constexpr uint8_t kBlockQuestion = 3;
constexpr uint8_t kBlockHard = 4;
constexpr uint8_t kBlockPipeTl = 5;
constexpr uint8_t kBlockPipeTr = 6;
constexpr uint8_t kBlockPipeBodyL = 7;
constexpr uint8_t kBlockPipeBodyR = 8;
constexpr uint8_t kBlockStair = 9;
constexpr uint8_t kBlockFlagPole = 10;
constexpr uint8_t kBlockCastle = 11;

constexpr uint16_t kBlockPx = 16;
constexpr uint16_t kScreenWidthPx = 160;
constexpr uint8_t kScyMax = 96;
constexpr uint16_t kMaxWorldX =
    (LEVEL_1_1_LENGTH_COLUMNS * kBlockPx > kScreenWidthPx)
        ? static_cast<uint16_t>(LEVEL_1_1_LENGTH_COLUMNS * kBlockPx - kScreenWidthPx)
        : uint16_t{0};

// tracks the rom's camera position by driving it exactly as main.c does: 2px per frame, one d-pad
// direction per axis, clamped the same way terrain.c clamps. the test never reads rom-private state.
struct Camera {
    uint16_t x = 0;
    uint8_t y = 0;

    void goto_xy(gb::Gameboy& gameboy, uint16_t target_x, uint8_t target_y) {
        while (x != target_x || y != target_y) {
            const bool right = x < target_x;
            const bool left = x > target_x;
            const bool down = y < target_y;
            const bool up = y > target_y;
            gameboy.set_button(gb::Button::Right, right);
            gameboy.set_button(gb::Button::Left, left);
            gameboy.set_button(gb::Button::Down, down);
            gameboy.set_button(gb::Button::Up, up);
            gameboy.run_frame();
            if (right) {
                x = static_cast<uint16_t>(x + 2);
            }
            if (left) {
                x = static_cast<uint16_t>(x - 2);
            }
            if (down) {
                y = static_cast<uint8_t>(y + 2);
            }
            if (up) {
                y = static_cast<uint8_t>(y - 2);
            }
        }
        gameboy.set_button(gb::Button::Right, false);
        gameboy.set_button(gb::Button::Left, false);
        gameboy.set_button(gb::Button::Down, false);
        gameboy.set_button(gb::Button::Up, false);
    }
};

// scy that brings block row `row` fully into the 144px window (see terrain.c's viewport math)
uint8_t scy_for_row(uint8_t row) {
    const uint16_t px = static_cast<uint16_t>(static_cast<uint16_t>(row) * kBlockPx);
    return static_cast<uint8_t>(px < kScyMax ? px : kScyMax);
}

// scx that brings block column `column` fully into the 160px window, clamped to the level's range
uint16_t scx_for_column(uint16_t column) {
    const uint16_t px = static_cast<uint16_t>(column * kBlockPx);
    return px < kMaxWorldX ? px : kMaxWorldX;
}

// the tile id at the world block (column, row)'s top-left 8x8 cell, given the camera sits at
// (cam_x, cam_y); the caller must have parked the camera so the block is actually on screen
uint8_t block_tile(const gb::Gameboy& gameboy, uint16_t column, uint8_t row, uint16_t cam_x, uint8_t cam_y) {
    const uint32_t screen_x = static_cast<uint32_t>(column) * kBlockPx - cam_x;
    const uint32_t screen_y = static_cast<uint32_t>(row) * kBlockPx - cam_y;
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    const uint16_t id = ids[(screen_y + 3) * gb::kLcdWidth + screen_x + 3];
    return static_cast<uint8_t>(id & 0xFFu);
}

// pinned bg tile family ranges per claude-docs/milestones/18-smbd.md's test/tile-id contract and
// the id map recorded in games/mario/src/assets.h
bool tile_in_kind_family(uint8_t tile, uint8_t kind) {
    switch (kind) {
    case kBlockEmpty:
        return tile == 0x00;
    case kBlockGround:
    case kBlockHard:
    case kBlockStair:
        return tile >= 0xA0 && tile <= 0xA3;
    case kBlockBrick:
        return tile >= 0xA4 && tile <= 0xA7;
    case kBlockQuestion:
        return tile >= 0xA8 && tile <= 0xAB;
    case kBlockPipeTl:
    case kBlockPipeTr:
    case kBlockPipeBodyL:
    case kBlockPipeBodyR:
        return tile >= 0xB0 && tile <= 0xB7;
    case kBlockFlagPole:
    case kBlockCastle:
        return tile >= 0xB8 && tile <= 0xBF;
    default:
        return false;
    }
}

// every family a terrain cell may legitimately render as: sky/ground/brick/question/hard/pipe/
// flag/castle share the 0xa0-0xbf block, and the font glyphs cover sky's reused space tile
bool is_known_terrain_family(uint8_t tile) {
    return tile <= 0x5F || (tile >= 0xA0 && tile <= 0xBF);
}

// --- sub-milestone 3: the player ---------------------------------------------------------------

// mirrors of games/mario/src/mario.h's player geometry, the same way kBlockPx above mirrors it
constexpr uint8_t kMarioFirstTile = 0xE0;
constexpr uint8_t kMarioTilesPerFrame = 4;
constexpr uint8_t kMarioFrameCount = 6;
constexpr uint8_t kMarioLastTile = kMarioFirstTile + kMarioFrameCount * kMarioTilesPerFrame - 1;
constexpr int kFrameIdle = 0;
constexpr int kFrameWalk0 = 1;
constexpr int kFrameWalk2 = 3;
constexpr int kFrameSkid = 4;
constexpr int kFrameJump = 5;
constexpr int kPlayerBoxPx = 16;
// the art keeps column 0 and column 15 of the 16px box transparent, so lit pixels sit one in
constexpr int kMarioArtInset = 1;
constexpr int kPlayScy = kScyMax;

// mario's world y while standing on the bible's start cell, in screen px (scy is pinned in play)
constexpr int kStandTop = static_cast<int>(LEVEL_1_1_START_ROW) * kBlockPx - kPlayerBoxPx - kPlayScy;

struct Mario {
    int left = 0;
    int right = 0;
    int top = 0;
    int frame = -1;
    bool found = false;
};

Mario mario_at(const gb::Gameboy& gameboy) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    Mario m;
    for (size_t i = 0; i < ids.size(); ++i) {
        if ((ids[i] & 0x100u) == 0) {
            continue;
        }
        const uint8_t tile = static_cast<uint8_t>(ids[i]);
        if (tile < kMarioFirstTile || tile > kMarioLastTile) {
            continue;
        }
        const int x = static_cast<int>(i % gb::kLcdWidth);
        const int y = static_cast<int>(i / gb::kLcdWidth);
        if (!m.found || x < m.left) {
            m.left = x;
        }
        if (!m.found || x > m.right) {
            m.right = x;
        }
        if (!m.found || y < m.top) {
            m.top = y;
        }
        m.frame = (tile - kMarioFirstTile) / kMarioTilesPerFrame;
        m.found = true;
    }
    return m;
}

// row 3 of the ground-top tile carries one dark speck every 4 px (see kGroundTiles in assets.c),
// so this scanline's first color-0 ground pixel gives the camera's position mod 4
constexpr int kGroundPhaseRow = 13 * kBlockPx + 3 - kPlayScy;

int ground_phase(const gb::Gameboy& gameboy) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    const std::span<const uint8_t> fb = gameboy.framebuffer();
    for (int x = 0; x < static_cast<int>(gb::kLcdWidth); ++x) {
        const size_t i = static_cast<size_t>(kGroundPhaseRow) * gb::kLcdWidth + static_cast<size_t>(x);
        if ((ids[i] & 0x100u) != 0) {
            continue;
        }
        if (static_cast<uint8_t>(ids[i]) == 0xA0 && fb[i] == 0) {
            return x % 4;
        }
    }
    return -1;
}

// the rom never exposes mario's world x, so the test reconstructs it: once the camera follows, his
// screen x is pinned and the whole displacement shows up in the camera's 4px phase; before that the
// camera is parked and it all shows up in his screen x. no step ever exceeds the 2.5 px/frame run
// cap, so the phase difference is unambiguous mod 4.
struct WorldTracker {
    int phase = 0;
    int screen = 0;

    void sync(const gb::Gameboy& gameboy, const Mario& m) {
        phase = ground_phase(gameboy);
        screen = m.left;
    }

    int step(const gb::Gameboy& gameboy, const Mario& m) {
        const int next = ground_phase(gameboy);
        const int cam = ((phase - next) % 4 + 4) % 4;
        const int moved = cam + (m.left - screen);
        phase = next;
        screen = m.left;
        return moved;
    }
};

// the bible's tables, generated straight from physics.json - the same header player.c reads
constexpr int8_t kJumpSpeed[kMarioJumpTierCount] = kMarioJumpSpeedInit;
constexpr uint8_t kGravityRise[kMarioJumpTierCount] = kMarioGravityRiseInit;
constexpr uint8_t kGravityFall[kMarioJumpTierCount] = kMarioGravityFallInit;

// host-side twin of player.c's vertical step: whole-px speed, a 1/256-px accumulator gravity feeds,
// and the bible's hold-a rule. tier 0 because every arc here starts from a standstill.
struct JumpSim {
    int y = kStandTop;
    int8_t speed = 0;
    uint8_t accum = 0;
    int origin = kStandTop;
    bool grounded = true;
    bool a_prev = false;

    void step(bool a) {
        if (grounded && a && !a_prev) {
            speed = kJumpSpeed[0];
            accum = 0;
            origin = y;
            grounded = false;
        }
        uint8_t force = kGravityFall[0];
        if (speed < 0 && ((a && a_prev) || (origin - y) < kMarioMinRisePx)) {
            force = kGravityRise[0];
        }
        const unsigned sum = static_cast<unsigned>(accum) + force;
        accum = static_cast<uint8_t>(sum);
        if (sum > 0xFFu) {
            speed = static_cast<int8_t>(speed + 1);
            if (speed > kMarioMaxFallPx) {
                speed = kMarioMaxFallPx;
            }
        }
        y += speed;
        // the start cell's floor is flat, so landing is one clamp back onto the standing row
        if (speed >= 0 && y >= kStandTop) {
            y = kStandTop;
            speed = 0;
            accum = 0;
            grounded = true;
        }
        a_prev = a;
    }
};

// drives one jump and returns mario's sprite top per frame. the rom reads the buttons set before
// run_frame i on its own frame i, but that frame is only scanned out one frame later, which is
// what the lag the callers measure accounts for.
std::vector<int> jump_tops(gb::Gameboy& gameboy, int hold_frames, int frames) {
    std::vector<int> tops;
    tops.reserve(static_cast<size_t>(frames));
    for (int i = 0; i < frames; ++i) {
        gameboy.set_button(gb::Button::A, i < hold_frames);
        gameboy.run_frame();
        const Mario m = mario_at(gameboy);
        REQUIRE(m.found);
        tops.push_back(m.top);
    }
    gameboy.set_button(gb::Button::A, false);
    return tops;
}

// the first frame mario's sprite actually moves; everything before it is the rom's scanout lag
int first_move(const std::vector<int>& tops) {
    for (size_t i = 0; i < tops.size(); ++i) {
        if (tops[i] != kStandTop) {
            return static_cast<int>(i);
        }
    }
    return -1;
}

// holds a direction (plus b to run) and returns the world px covered over the whole window
int travel(gb::Gameboy& gameboy, gb::Button dir, bool run_button, int frames) {
    WorldTracker tracker;
    tracker.sync(gameboy, mario_at(gameboy));
    gameboy.set_button(dir, true);
    gameboy.set_button(gb::Button::B, run_button);
    int total = 0;
    for (int i = 0; i < frames; ++i) {
        gameboy.run_frame();
        total += tracker.step(gameboy, mario_at(gameboy));
    }
    return total;
}

// the leftmost screen x carrying a bg pipe pixel on mario's own rows, or -1
int pipe_face(const gb::Gameboy& gameboy, const Mario& m) {
    const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
    for (int x = 0; x < static_cast<int>(gb::kLcdWidth); ++x) {
        for (int y = m.top; y < m.top + kPlayerBoxPx; ++y) {
            const size_t i = static_cast<size_t>(y) * gb::kLcdWidth + static_cast<size_t>(x);
            if ((ids[i] & 0x100u) != 0) {
                continue;
            }
            const uint8_t tile = static_cast<uint8_t>(ids[i]);
            if (tile >= 0xB0 && tile <= 0xB7) {
                return x;
            }
        }
    }
    return -1;
}

// the level's first pit, taken from the compiler's own probes rather than the bible's json
uint16_t first_gap_column() {
    for (const auto& probe : kLevel11Probes) {
        if (probe.kind == kBlockEmpty && probe.row == 13) {
            return probe.column;
        }
    }
    return 0;
}

} // namespace

TEST_CASE("mario_rom_declares_a_cgb_mbc5_cart") {
    const std::vector<uint8_t> rom = read_mario_rom();
    REQUIRE(rom.size() == 131072u);

    std::string why;
    auto cart = gb::Cartridge::parse(rom, &why);
    REQUIRE(why.empty());
    REQUIRE(cart.has_value());
    REQUIRE(cart->type() == gb::CartType::Mbc5);
    REQUIRE(cart->has_battery());
    REQUIRE(cart->ram_size() > 0u);
    REQUIRE(cart->cgb());
    REQUIRE(cart->title() == "MARIO");
}

TEST_CASE("mario_boots_to_a_colored_title") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    run(gameboy, kBootFrames);
    REQUIRE(gameboy.cgb_mode());

    const std::span<const uint16_t> colors = gameboy.framebuffer_color();
    std::set<uint16_t> distinct(colors.begin(), colors.end());
    REQUIRE(distinct.size() >= 4u);

    size_t non_gray = 0;
    for (uint16_t c : distinct) {
        if (is_non_gray(c)) {
            ++non_gray;
        }
    }
    REQUIRE(non_gray >= 2u);
}

TEST_CASE("mario_title_text_is_centered") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    run(gameboy, kBootFrames);

    // even-length lines land symmetric around the 20 column grid: left + right == 19
    for (uint32_t row : {kTitleRow, kPromptRow}) {
        const auto [left, right] = glyph_span(gameboy, row, kFontFirstTile + 1, kFontLastTile);
        REQUIRE(left >= 0);
        REQUIRE(left + right == 19);
    }
}

TEST_CASE("mario_boot_is_deterministic") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy first;
    gb::Gameboy second;
    REQUIRE(first.load_rom(rom));
    REQUIRE(second.load_rom(rom));
    run(first, kBootFrames);
    run(second, kBootFrames);

    const std::span<const uint16_t> a = first.framebuffer_color();
    const std::span<const uint16_t> b = second.framebuffer_color();
    REQUIRE(a.size() == b.size());
    REQUIRE(std::equal(a.begin(), a.end(), b.begin()));
}

// the golden test binding bible -> compiler -> rom -> screen: every probe the compiler derived
// from level-1-1.json's terrain runs and blocks must render its expected tile family once its
// block is actually on screen. the test never hand-duplicates the bible's positions.
TEST_CASE("mario_compiler_probes_match_the_rendered_level") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    Camera camera;
    for (uint16_t i = 0; i < kLevel11ProbeCount; ++i) {
        const LevelProbe& probe = kLevel11Probes[i];
        camera.goto_xy(gameboy, scx_for_column(probe.column), scy_for_row(probe.row));
        const uint8_t tile = block_tile(gameboy, probe.column, probe.row, camera.x, camera.y);
        REQUIRE(tile_in_kind_family(tile, probe.kind));
    }
}

TEST_CASE("mario_terrain_streams_without_garbage") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    Camera camera;
    const auto check_visible_cells = [&]() {
        const std::span<const uint16_t> ids = gameboy.framebuffer_tiles();
        for (uint32_t ty = 0; ty < 18; ++ty) {
            for (uint32_t tx = 0; tx < 20; ++tx) {
                const uint16_t id = ids[(ty * 8 + 3) * gb::kLcdWidth + tx * 8 + 3];
                REQUIRE(is_known_terrain_family(static_cast<uint8_t>(id & 0xFFu)));
            }
        }
    };

    // scroll the whole derived level, one block at a time, checking every visible cell at each stop
    check_visible_cells();
    while (camera.x < kMaxWorldX) {
        const uint16_t step = std::min<uint16_t>(kBlockPx, static_cast<uint16_t>(kMaxWorldX - camera.x));
        camera.goto_xy(gameboy, static_cast<uint16_t>(camera.x + step), camera.y);
        check_visible_cells();
    }
}

TEST_CASE("mario_scy_pans_within_range") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    const LevelProbe* flag_probe = nullptr;
    for (const auto& probe : kLevel11Probes) {
        if (probe.kind == kBlockFlagPole) {
            flag_probe = &probe;
            break;
        }
    }
    REQUIRE(flag_probe != nullptr);

    Camera camera;
    camera.goto_xy(gameboy, scx_for_column(flag_probe->column), scy_for_row(flag_probe->row));
    REQUIRE(tile_in_kind_family(block_tile(gameboy, flag_probe->column, flag_probe->row, camera.x, camera.y),
                                kBlockFlagPole));

    // panning all the way down scrolls the pole's high row above the window, out of view
    camera.goto_xy(gameboy, camera.x, kScyMax);
    const uint8_t bottom_tile = block_tile(gameboy, flag_probe->column, 14, camera.x, camera.y);
    REQUIRE(tile_in_kind_family(bottom_tile, kBlockGround));

    // holding down well past the max cannot push scy outside the level's 240px height
    press(gameboy, gb::Button::Down, 40);
    REQUIRE(block_tile(gameboy, flag_probe->column, 14, camera.x, camera.y) == bottom_tile);

    // panning back up brings the pole's row back into view
    camera.goto_xy(gameboy, camera.x, scy_for_row(flag_probe->row));
    REQUIRE(tile_in_kind_family(block_tile(gameboy, flag_probe->column, flag_probe->row, camera.x, camera.y),
                                kBlockFlagPole));
}

TEST_CASE("mario_camera_shows_colored_terrain") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_camera(gameboy);

    // columns 20-29 hold the opening brick/question pyramid and the first pipe; rows 6-14 (scy
    // maxed) keep both those and the row 13-14 ground on screen together
    Camera camera;
    camera.goto_xy(gameboy, scx_for_column(20), scy_for_row(13));

    const std::span<const uint16_t> colors = gameboy.framebuffer_color();
    const std::set<uint16_t> distinct(colors.begin(), colors.end());
    size_t non_gray = 0;
    for (uint16_t c : distinct) {
        if (is_non_gray(c)) {
            ++non_gray;
        }
    }
    REQUIRE(non_gray >= 5u);
}

TEST_CASE("mario_spawns_standing_on_the_bible_start_cell") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    const Mario m = mario_at(gameboy);
    REQUIRE(m.found);
    REQUIRE(m.top == kStandTop);
    REQUIRE(m.left == static_cast<int>(LEVEL_1_1_START_COLUMN) * kBlockPx + kMarioArtInset);
    REQUIRE(m.right - m.left == kPlayerBoxPx - 1 - 2 * kMarioArtInset);
    REQUIRE(m.frame == kFrameIdle);
}

// the milestone's heart: the arc the rom draws must equal the arc the bible's own constants
// predict, simulated host side with the same 1/256 accumulator semantics, frame for frame
TEST_CASE("mario_golden_jump_arc") {
    const std::vector<uint8_t> rom = read_mario_rom();

    constexpr int kArcFrames = 70;
    gb::Gameboy held;
    REQUIRE(held.load_rom(rom));
    enter_play(held);
    const std::vector<int> hold_tops = jump_tops(held, kArcFrames, kArcFrames);

    const int lag = first_move(hold_tops);
    REQUIRE(lag >= 0);
    REQUIRE(lag <= 2);

    JumpSim sim;
    for (size_t i = static_cast<size_t>(lag); i < hold_tops.size(); ++i) {
        sim.step(true);
        REQUIRE(hold_tops[i] == sim.y);
    }
    // the held arc has to be an arc, not a flat line
    REQUIRE(*std::min_element(hold_tops.begin(), hold_tops.end()) < kStandTop - 60);
    REQUIRE(hold_tops.back() == kStandTop);
}

TEST_CASE("mario_tapped_jump_arc_is_shorter_than_the_held_one") {
    const std::vector<uint8_t> rom = read_mario_rom();

    constexpr int kArcFrames = 70;
    constexpr int kTapFrames = 4;
    gb::Gameboy held;
    REQUIRE(held.load_rom(rom));
    enter_play(held);
    const std::vector<int> hold_tops = jump_tops(held, kArcFrames, kArcFrames);
    const int lag = first_move(hold_tops);
    REQUIRE(lag >= 0);

    gb::Gameboy tapped;
    REQUIRE(tapped.load_rom(rom));
    enter_play(tapped);
    const std::vector<int> tap_tops = jump_tops(tapped, kTapFrames, kArcFrames);
    REQUIRE(first_move(tap_tops) == lag);

    JumpSim sim;
    for (size_t i = static_cast<size_t>(lag); i < tap_tops.size(); ++i) {
        sim.step(static_cast<int>(i) - lag < kTapFrames);
        REQUIRE(tap_tops[i] == sim.y);
    }

    // the hold mechanic is the whole point: releasing early cuts the rise off hard
    const int tap_peak = *std::min_element(tap_tops.begin(), tap_tops.end());
    const int hold_peak = *std::min_element(hold_tops.begin(), hold_tops.end());
    REQUIRE(tap_peak > hold_peak + 20);
    REQUIRE(tap_tops.back() == kStandTop);
}

TEST_CASE("mario_max_speeds_match_the_bible") {
    const std::vector<uint8_t> rom = read_mario_rom();

    constexpr int kRunUp = 80;
    constexpr int kMeasure = 40;
    const auto converged = [&rom](bool run_button) {
        gb::Gameboy gameboy;
        REQUIRE(gameboy.load_rom(rom));
        enter_play(gameboy);
        travel(gameboy, gb::Button::Right, run_button, kRunUp);
        const int moved = travel(gameboy, gb::Button::Right, run_button, kMeasure);
        return static_cast<double>(moved) / kMeasure;
    };

    // 24 and 40 subpixels a frame, 16 subpixels to the pixel; the alternating whole-px steps
    // average out exactly, so a twentieth of a pixel is all the slack this needs
    REQUIRE(std::abs(converged(false) - kMarioMaxWalkSubpx / 16.0) < 0.05);
    REQUIRE(std::abs(converged(true) - kMarioMaxRunSubpx / 16.0) < 0.05);
}

TEST_CASE("mario_skid_turns_slower_than_release") {
    const std::vector<uint8_t> rom = read_mario_rom();

    constexpr int kRunUp = 80;
    constexpr int kCap = 200;
    // px still covered to the right after the run-up, until mario is done shedding that speed
    const auto coast = [&rom](bool reverse) {
        gb::Gameboy gameboy;
        REQUIRE(gameboy.load_rom(rom));
        enter_play(gameboy);
        travel(gameboy, gb::Button::Right, false, kRunUp);
        gameboy.set_button(gb::Button::Right, false);
        gameboy.set_button(gb::Button::Left, reverse);

        WorldTracker tracker;
        tracker.sync(gameboy, mario_at(gameboy));
        int total = 0;
        for (int i = 0; i < kCap; ++i) {
            gameboy.run_frame();
            const Mario m = mario_at(gameboy);
            REQUIRE(m.found);
            total += tracker.step(gameboy, m);
            // a release ends at the idle pose, a reversal the frame the skid pose drops
            if (reverse ? m.frame != kFrameSkid : m.frame == kFrameIdle) {
                break;
            }
        }
        gameboy.set_button(gb::Button::Left, false);
        return total;
    };

    const int released = coast(false);
    const int skidded = coast(true);
    REQUIRE(released > 0);
    REQUIRE(skidded > 0);
    // the bible doubles whichever accel tier applies while facing fights motion
    REQUIRE(skidded * 2 < released);
}

TEST_CASE("mario_wall_stops_motion") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    // 1-1's first pipe is a few hundred px out; running there takes well under this many frames
    travel(gameboy, gb::Button::Right, true, 260);
    const Mario m = mario_at(gameboy);
    REQUIRE(m.found);
    REQUIRE(m.top == kStandTop);

    // flush: the box's right edge sits one px left of the pipe face, the art one px inside that
    const int face = pipe_face(gameboy, m);
    REQUIRE(face >= 0);
    REQUIRE(m.right == face - 1 - kMarioArtInset);

    // nothing moves while the wall is held against
    const int moved = travel(gameboy, gb::Button::Right, true, 60);
    REQUIRE(moved == 0);
    const Mario after = mario_at(gameboy);
    REQUIRE(after.top == kStandTop);
    REQUIRE(pipe_face(gameboy, after) == face);
}

TEST_CASE("mario_landing_snaps_without_sinking") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);

    // 600 frames of hopping in place, checking he never sinks past the row he took off from
    int hops = 0;
    for (int i = 0; i < 600; ++i) {
        gameboy.set_button(gb::Button::A, (i % 60) < 8);
        gameboy.run_frame();
        const Mario m = mario_at(gameboy);
        REQUIRE(m.found);
        REQUIRE(m.top <= kStandTop);
        if (m.frame == kFrameJump) {
            ++hops;
        }
    }
    gameboy.set_button(gb::Button::A, false);
    run(gameboy, 60);
    REQUIRE(hops > 100);
    REQUIRE(mario_at(gameboy).top == kStandTop);
}

TEST_CASE("mario_animation_changes_with_state") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);
    REQUIRE(mario_at(gameboy).frame == kFrameIdle);

    std::set<int> walking;
    gameboy.set_button(gb::Button::Right, true);
    for (int i = 0; i < 90; ++i) {
        gameboy.run_frame();
        const Mario m = mario_at(gameboy);
        REQUIRE(m.found);
        if (m.frame >= kFrameWalk0 && m.frame <= kFrameWalk2) {
            walking.insert(m.frame);
        }
    }
    REQUIRE(walking.size() >= 2u);

    // a jump swaps in the jump pose for the airborne stretch
    std::set<int> airborne;
    gameboy.set_button(gb::Button::A, true);
    for (int i = 0; i < 20; ++i) {
        gameboy.run_frame();
        airborne.insert(mario_at(gameboy).frame);
    }
    gameboy.set_button(gb::Button::A, false);
    gameboy.set_button(gb::Button::Right, false);
    REQUIRE(airborne.count(kFrameJump) == 1u);

    // reversing at speed shows the skid pose
    run(gameboy, 60);
    gameboy.set_button(gb::Button::Right, true);
    run(gameboy, 60);
    gameboy.set_button(gb::Button::Right, false);
    gameboy.set_button(gb::Button::Left, true);
    std::set<int> turning;
    for (int i = 0; i < 8; ++i) {
        gameboy.run_frame();
        turning.insert(mario_at(gameboy).frame);
    }
    gameboy.set_button(gb::Button::Left, false);
    REQUIRE(turning.count(kFrameSkid) == 1u);
}

TEST_CASE("mario_pit_respawns_him_at_the_start") {
    const std::vector<uint8_t> rom = read_mario_rom();

    gb::Gameboy gameboy;
    REQUIRE(gameboy.load_rom(rom));
    enter_play(gameboy);
    REQUIRE(first_gap_column() > 0u);

    // autopilot to the level's first pit: run right, and jump whenever a pipe face is close
    // enough ahead to need clearing. the release frame between jumps gives the next its edge.
    gameboy.set_button(gb::Button::Right, true);
    gameboy.set_button(gb::Button::B, true);
    bool a_held = false;
    bool fell = false;
    int last_top = kStandTop;
    for (int frames = 0; frames < 1200 && !fell; ++frames) {
        const Mario m = mario_at(gameboy);
        if (!m.found) {
            // gone downward is the pit; a jump from a pipe top can clip him off the top instead
            fell = last_top > kStandTop;
            if (fell) {
                break;
            }
            gameboy.run_frame();
            continue;
        }
        last_top = m.top;
        const int face = pipe_face(gameboy, m);
        if (m.frame == kFrameJump) {
            a_held = true;
        } else if (a_held) {
            a_held = false;
        } else {
            a_held = face >= 0 && face - m.right <= 48;
        }
        gameboy.set_button(gb::Button::A, a_held);
        gameboy.run_frame();
    }
    REQUIRE(fell);

    // and he is back on the bible's start cell once the respawn has settled
    gameboy.set_button(gb::Button::Right, false);
    gameboy.set_button(gb::Button::B, false);
    gameboy.set_button(gb::Button::A, false);
    run(gameboy, 90);
    const Mario back = mario_at(gameboy);
    REQUIRE(back.found);
    REQUIRE(back.top == kStandTop);
    REQUIRE(back.left == static_cast<int>(LEVEL_1_1_START_COLUMN) * kBlockPx + kMarioArtInset);
}

TEST_CASE("mario_play_is_deterministic") {
    const std::vector<uint8_t> rom = read_mario_rom();

    const auto drive = [&rom]() {
        gb::Gameboy gameboy;
        REQUIRE(gameboy.load_rom(rom));
        enter_play(gameboy);
        for (int i = 0; i < 240; ++i) {
            gameboy.set_button(gb::Button::Right, (i % 40) < 30);
            gameboy.set_button(gb::Button::B, (i % 80) < 40);
            gameboy.set_button(gb::Button::A, (i % 25) < 10);
            gameboy.run_frame();
        }
        const std::span<const uint16_t> colors = gameboy.framebuffer_color();
        return std::vector<uint16_t>(colors.begin(), colors.end());
    };

    REQUIRE(drive() == drive());
}
